export const collegeDatabase = {
  kerala: [
    // ─── GOVERNMENT ENGINEERING ────────────────────────────────────────────
    { name: "College of Engineering, Thiruvananthapuram (CET)", state: "Kerala", location: "Thiruvananthapuram", availableCourses: ["btech-cse", "ai-ml", "robotics", "architecture", "renewable-energy", "iot-engineering", "cybersecurity"], fees: "₹35,000 / year", avgPackage: "₹6.5L", highestPackage: "₹38L", placementScore: 92, website: "https://www.cet.ac.in", category: "Government", rating: 4.6, ranking: 1, admissionDifficulty: "Very High" },
    { name: "Government Engineering College, Thrissur (GEC Thrissur)", state: "Kerala", location: "Thrissur", availableCourses: ["btech-cse", "robotics", "architecture", "renewable-energy", "ai-ml"], fees: "₹35,000 / year", avgPackage: "₹6.2L", highestPackage: "₹32L", placementScore: 91, website: "https://www.gectcr.ac.in", category: "Government", rating: 4.5, ranking: 2, admissionDifficulty: "Very High" },
    { name: "Government Engineering College, Barton Hill", state: "Kerala", location: "Thiruvananthapuram", availableCourses: ["btech-cse", "robotics", "renewable-energy", "iot-engineering"], fees: "₹38,000 / year", avgPackage: "₹6.0L", highestPackage: "₹28L", placementScore: 90, website: "https://www.gecbh.ac.in", category: "Government", rating: 4.4, ranking: 3, admissionDifficulty: "High" },
    { name: "NIT Calicut (NITC)", state: "Kerala", location: "Kozhikode", availableCourses: ["btech-cse", "ai-ml", "robotics", "architecture", "renewable-energy", "machine-learning", "blockchain-dev"], fees: "₹1.5L / year", avgPackage: "₹9L", highestPackage: "₹50L", placementScore: 96, website: "https://www.nitc.ac.in", category: "Government", rating: 4.7, ranking: 1, admissionDifficulty: "Extremely High" },
    { name: "TKM College of Engineering", state: "Kerala", location: "Kollam", availableCourses: ["btech-cse", "robotics", "architecture", "renewable-energy", "iot-engineering"], fees: "₹38,000 / year", avgPackage: "₹5.8L", highestPackage: "₹28L", placementScore: 88, website: "https://www.tkmce.ac.in", category: "Government", rating: 4.4, ranking: 4, admissionDifficulty: "High" },
    { name: "Mar Athanasius College of Engineering (MACE)", state: "Kerala", location: "Kothamangalam", availableCourses: ["btech-cse", "robotics", "renewable-energy", "iot-engineering"], fees: "₹35,000 / year", avgPackage: "₹5.5L", highestPackage: "₹25L", placementScore: 86, website: "https://www.mace.ac.in", category: "Government", rating: 4.3, ranking: 5, admissionDifficulty: "High" },
    { name: "NSS College of Engineering, Palakkad", state: "Kerala", location: "Palakkad", availableCourses: ["btech-cse", "robotics", "renewable-energy"], fees: "₹32,000 / year", avgPackage: "₹5.2L", highestPackage: "₹20L", placementScore: 82, website: "https://www.nssce.ac.in", category: "Government", rating: 4.2, ranking: 6, admissionDifficulty: "High" },
    { name: "Wayanad Government Engineering College", state: "Kerala", location: "Wayanad", availableCourses: ["btech-cse", "renewable-energy"], fees: "₹30,000 / year", avgPackage: "₹4.5L", highestPackage: "₹18L", placementScore: 78, website: "https://www.gecwyd.ac.in", category: "Government", rating: 4.1, ranking: 8, admissionDifficulty: "Moderate" },
    { name: "Jyothi Engineering College (JECC)", state: "Kerala", location: "Thrissur", availableCourses: ["btech-cse", "ai-ml", "iot-engineering", "cybersecurity"], fees: "₹72,000 / year", avgPackage: "₹4.8L", highestPackage: "₹20L", placementScore: 81, website: "https://www.jecc.ac.in", category: "Private", rating: 4.1, ranking: 12, admissionDifficulty: "Moderate" },

    // ─── PRIVATE ENGINEERING ───────────────────────────────────────────────
    { name: "Cochin University of Science and Technology (CUSAT)", state: "Kerala", location: "Kochi", availableCourses: ["btech-cse", "ai-ml", "biotech", "marine-eng", "machine-learning", "software-testing", "data-science"], fees: "₹65,000 / year", avgPackage: "₹6.2L", highestPackage: "₹40L", placementScore: 89, website: "https://www.cusat.ac.in", category: "Government", rating: 4.4, ranking: 2, admissionDifficulty: "Very High" },
    { name: "Government Model Engineering College (MEC)", state: "Kerala", location: "Kochi", availableCourses: ["btech-cse", "ai-ml", "robotics", "biomedical-eng", "cloud-computing", "robot-vision"], fees: "₹40,000 / year", avgPackage: "₹7.5L", highestPackage: "₹32L", placementScore: 95, website: "https://www.mec.ac.in", category: "Government", rating: 4.5, ranking: 3, admissionDifficulty: "Very High" },
    { name: "Saintgits College of Engineering", state: "Kerala", location: "Kottayam", availableCourses: ["btech-cse", "ai-ml", "robotics", "cloud-computing", "iot-engineering", "cybersecurity"], fees: "₹75,000 / year", avgPackage: "₹4.8L", highestPackage: "₹22L", placementScore: 83, website: "https://www.saintgits.org", category: "Private", rating: 4.2, ranking: 9, admissionDifficulty: "Moderate" },
    { name: "Federal Institute of Science and Technology (FISAT)", state: "Kerala", location: "Angamaly", availableCourses: ["btech-cse", "ai-ml", "cloud-computing", "cybersecurity", "software-testing", "data-science"], fees: "₹80,000 / year", avgPackage: "₹5.1L", highestPackage: "₹24L", placementScore: 85, website: "https://www.fisat.ac.in", category: "Private", rating: 4.3, ranking: 10, admissionDifficulty: "Moderate" },
    { name: "Amal Jyothi College of Engineering (AJCE)", state: "Kerala", location: "Kanjirappally", availableCourses: ["btech-cse", "robotics", "food-tech", "renewable-energy", "iot-engineering"], fees: "₹85,000 / year", avgPackage: "₹4.8L", highestPackage: "₹24L", placementScore: 84, website: "https://www.amaljyothi.ac.in", category: "Private", rating: 4.3, ranking: 11, admissionDifficulty: "Moderate" },
    { name: "Sahrdaya College of Engineering (SCET)", state: "Kerala", location: "Kodakara", availableCourses: ["biomedical-eng", "biotech", "btech-cse", "renewable-energy"], fees: "₹85,000 / year", avgPackage: "₹4.6L", highestPackage: "₹18L", placementScore: 81, website: "https://sahrdaya.ac.in", category: "Private", rating: 4.2, ranking: 13, admissionDifficulty: "Moderate" },
    { name: "Muthoot Institute of Technology and Science (MITS Kochi)", state: "Kerala", location: "Kochi", availableCourses: ["btech-cse", "ai-ml", "cybersecurity", "software-testing", "data-science"], fees: "₹90,000 / year", avgPackage: "₹5.2L", highestPackage: "₹26L", placementScore: 86, website: "https://www.mgmits.ac.in", category: "Private", rating: 4.4, ranking: 14, admissionDifficulty: "Moderate" },
    { name: "Ilahia College of Engineering and Technology", state: "Kerala", location: "Ernakulam", availableCourses: ["btech-cse", "ai-ml", "iot-engineering", "cloud-computing"], fees: "₹78,000 / year", avgPackage: "₹4.5L", highestPackage: "₹18L", placementScore: 80, website: "https://www.ilahia.ac.in", category: "Private", rating: 4.0, ranking: 15, admissionDifficulty: "Moderate" },
    { name: "AWH Engineering College", state: "Kerala", location: "Kozhikode", availableCourses: ["btech-cse", "robotics", "ai-ml", "cybersecurity"], fees: "₹74,000 / year", avgPackage: "₹4.2L", highestPackage: "₹16L", placementScore: 79, website: "https://www.awhengg.org", category: "Private", rating: 4.0, ranking: 16, admissionDifficulty: "Moderate" },
    { name: "KMCT College of Engineering", state: "Kerala", location: "Kozhikode", availableCourses: ["btech-cse", "ai-ml", "cloud-computing"], fees: "₹70,000 / year", avgPackage: "₹4.0L", highestPackage: "₹15L", placementScore: 77, website: "https://www.kmct.ac.in", category: "Private", rating: 3.9, ranking: 17, admissionDifficulty: "Low" },
    { name: "ASIET - Adoor", state: "Kerala", location: "Adoor", availableCourses: ["btech-cse", "iot-engineering", "renewable-energy"], fees: "₹68,000 / year", avgPackage: "₹4.0L", highestPackage: "₹14L", placementScore: 76, website: "https://www.asiet.ac.in", category: "Private", rating: 3.9, ranking: 18, admissionDifficulty: "Low" },
    { name: "UKF College of Engineering", state: "Kerala", location: "Kollam", availableCourses: ["btech-cse", "iot-engineering", "renewable-energy"], fees: "₹65,000 / year", avgPackage: "₹3.8L", highestPackage: "₹12L", placementScore: 75, website: "https://www.ukfce.ac.in", category: "Private", rating: 3.8, ranking: 19, admissionDifficulty: "Low" },
    { name: "Nehru College of Engineering", state: "Kerala", location: "Thrissur", availableCourses: ["btech-cse", "ai-ml", "software-testing"], fees: "₹72,000 / year", avgPackage: "₹4.0L", highestPackage: "₹14L", placementScore: 78, website: "https://ncepune.ac.in", category: "Private", rating: 4.0, ranking: 20, admissionDifficulty: "Moderate" },
    { name: "Baselios Mathews II College of Engineering", state: "Kerala", location: "Pathanamthitta", availableCourses: ["btech-cse", "renewable-energy", "iot-engineering"], fees: "₹66,000 / year", avgPackage: "₹3.8L", highestPackage: "₹13L", placementScore: 74, website: "https://www.bmce.ac.in", category: "Private", rating: 3.8, ranking: 21, admissionDifficulty: "Low" },
    { name: "LBS Institute of Technology for Women", state: "Kerala", location: "Thiruvananthapuram", availableCourses: ["btech-cse", "ai-ml", "cybersecurity"], fees: "₹35,000 / year", avgPackage: "₹5L", highestPackage: "₹22L", placementScore: 83, website: "https://www.lbitw.ac.in", category: "Government", rating: 4.2, ranking: 7, admissionDifficulty: "High" },
    { name: "Vidya Academy of Science & Technology", state: "Kerala", location: "Thrissur", availableCourses: ["btech-cse", "ai-ml", "robotics", "software-testing"], fees: "₹75,000 / year", avgPackage: "₹4.2L", highestPackage: "₹18L", placementScore: 79, website: "https://www.vidyaacademy.ac.in", category: "Private", rating: 4.0, ranking: 22, admissionDifficulty: "Moderate" },
    { name: "Toc H Institute of Science and Technology", state: "Kerala", location: "Kochi", availableCourses: ["btech-cse", "ai-ml", "iot-engineering", "cloud-computing"], fees: "₹80,000 / year", avgPackage: "₹4.5L", highestPackage: "₹20L", placementScore: 81, website: "https://www.tistcochin.edu.in", category: "Private", rating: 4.1, ranking: 23, admissionDifficulty: "Moderate" },

    // ─── BUSINESS SCHOOLS ─────────────────────────────────────────────────
    { name: "IIM Kozhikode (IIMK)", state: "Kerala", location: "Kozhikode", availableCourses: ["bba", "mba-integrated", "finance-path", "intl-business", "biz-analytics", "hrm", "family-business", "product-mgmt"], fees: "₹20L total", avgPackage: "₹29L", highestPackage: "₹72L", placementScore: 99, website: "https://www.iimk.ac.in", category: "Government", rating: 4.9, ranking: 1, admissionDifficulty: "Extremely High" },
    { name: "SCMS School of Technology and Management", state: "Kerala", location: "Kochi", availableCourses: ["bba", "finance-path", "digital-marketing", "supply-chain", "ecommerce", "investment-mgmt", "biz-analytics"], fees: "₹1.2L / year", avgPackage: "₹4.5L", highestPackage: "₹15L", placementScore: 82, website: "https://www.scmsgroup.org", category: "Private", rating: 4.1, ranking: 3, admissionDifficulty: "Moderate" },
    { name: "XIME Kochi", state: "Kerala", location: "Kochi", availableCourses: ["mba-integrated", "biz-analytics", "hrm", "intl-business", "brand-mgmt"], fees: "₹8L total", avgPackage: "₹8L", highestPackage: "₹22L", placementScore: 87, website: "https://www.ximekochi.org", category: "Private", rating: 4.3, ranking: 2, admissionDifficulty: "High" },
    { name: "Rajagiri Business School", state: "Kerala", location: "Kochi", availableCourses: ["mba-integrated", "hrm", "bba", "intl-business", "supply-chain"], fees: "₹3.5L / year", avgPackage: "₹7.5L", highestPackage: "₹24L", placementScore: 89, website: "https://www.rajagiribusinessschool.edu.in", category: "Private", rating: 4.6, ranking: 4, admissionDifficulty: "High" },
    { name: "Christ Nagar College Thiruvananthapuram", state: "Kerala", location: "Thiruvananthapuram", availableCourses: ["bba", "economics", "journalism", "digital-marketing"], fees: "₹40,000 / year", avgPackage: "₹3.8L", highestPackage: "₹12L", placementScore: 78, website: "https://www.christnagar.ac.in", category: "Private", rating: 4.1, ranking: 6, admissionDifficulty: "Low" },
    { name: "Marian College Kuttikkanam", state: "Kerala", location: "Idukki", availableCourses: ["bba", "economics", "vis-comm", "social-work", "travel-tourism", "digital-media"], fees: "₹50,000 / year", avgPackage: "₹4L", highestPackage: "₹12L", placementScore: 80, website: "https://www.mariancollege.org", category: "Private", rating: 4.3, ranking: 5, admissionDifficulty: "Moderate" },
    { name: "ICA Edu Skills", state: "Kerala", location: "Multiple", availableCourses: ["ca", "acca", "fintech", "banking-finance", "investment-mgmt"], fees: "₹60,000 / year", avgPackage: "₹5L", highestPackage: "₹18L", placementScore: 82, website: "https://www.icaeduskills.in", category: "Private", rating: 4.0, ranking: 7, admissionDifficulty: "Low" },
    { name: "St. Albert's College", state: "Kerala", location: "Kochi", availableCourses: ["bba", "travel-tourism", "supply-chain", "ecommerce", "event-mgmt"], fees: "₹42,000 / year", avgPackage: "₹4L", highestPackage: "₹12L", placementScore: 79, website: "https://alberts.edu.in", category: "Private", rating: 4.2, ranking: 8, admissionDifficulty: "Moderate" },
    { name: "MACFAST (Malankara Catholic College)", state: "Kerala", location: "Tiruvalla", availableCourses: ["biotech", "food-tech", "bba", "biz-analytics", "supply-chain-ops"], fees: "₹90,000 / year", avgPackage: "₹4.5L", highestPackage: "₹14L", placementScore: 80, website: "https://www.macfast.org", category: "Private", rating: 4.2, ranking: 9, admissionDifficulty: "Moderate" },
    { name: "DC School of Design", state: "Kerala", location: "Kottayam", availableCourses: ["ui-ux", "graphic-design", "product-design", "animation", "fashion-design", "interior-design"], fees: "₹1.2L / year", avgPackage: "₹4.5L", highestPackage: "₹14L", placementScore: 82, website: "https://www.dcschool.ac.in", category: "Private", rating: 4.3, ranking: 2, admissionDifficulty: "Moderate" },

    // ─── ARTS & SCIENCE / HUMANITIES ──────────────────────────────────────
    { name: "Farook College", state: "Kerala", location: "Kozhikode", availableCourses: ["economics", "journalism", "vis-comm", "psychology", "digital-media"], fees: "₹30,000 / year", avgPackage: "₹3.8L", highestPackage: "₹12L", placementScore: 76, website: "https://www.farookcollege.ac.in", category: "Private", rating: 4.4, ranking: 4, admissionDifficulty: "Moderate" },
    { name: "Sacred Heart College (SH College)", state: "Kerala", location: "Kochi", availableCourses: ["vis-comm", "journalism", "economics", "psychology", "digital-marketing", "pr-corporate"], fees: "₹40,000 / year", avgPackage: "₹4.2L", highestPackage: "₹14L", placementScore: 81, website: "https://www.shcollege.ac.in", category: "Private", rating: 4.5, ranking: 3, admissionDifficulty: "Moderate" },
    { name: "St. Thomas College Thrissur", state: "Kerala", location: "Thrissur", availableCourses: ["economics", "psychology", "vis-comm", "social-work", "journalism"], fees: "₹36,000 / year", avgPackage: "₹4.0L", highestPackage: "₹14L", placementScore: 81, website: "https://stthomas.ac.in", category: "Private", rating: 4.4, ranking: 5, admissionDifficulty: "Moderate" },
    { name: "St. Teresa's College Ernakulam", state: "Kerala", location: "Kochi", availableCourses: ["fashion-design", "interior-design", "clinical-psychology", "teaching", "early-edu", "textile-design", "fashion-styling", "psychology"], fees: "₹45,000 / year", avgPackage: "₹4L", highestPackage: "₹12L", placementScore: 80, website: "https://www.teresas.ac.in", category: "Private", rating: 4.5, ranking: 2, admissionDifficulty: "Moderate" },
    { name: "Providence College", state: "Kerala", location: "Kozhikode", availableCourses: ["psychology", "economics", "journalism", "social-work", "digital-media"], fees: "₹32,000 / year", avgPackage: "₹3.6L", highestPackage: "₹10L", placementScore: 75, website: "https://www.providence.edu.in", category: "Private", rating: 4.2, ranking: 6, admissionDifficulty: "Low" },
    { name: "Vimala College Thrissur", state: "Kerala", location: "Thrissur", availableCourses: ["psychology", "fashion-design", "economics", "teaching", "early-edu"], fees: "₹34,000 / year", avgPackage: "₹3.9L", highestPackage: "₹12L", placementScore: 79, website: "https://vimalacollege.edu.in", category: "Private", rating: 4.3, ranking: 7, admissionDifficulty: "Moderate" },
    { name: "SN College Kollam", state: "Kerala", location: "Kollam", availableCourses: ["economics", "psychology", "vis-comm", "social-work"], fees: "₹28,000 / year", avgPackage: "₹3.5L", highestPackage: "₹10L", placementScore: 74, website: "https://www.sncollegekollam.ac.in", category: "Government", rating: 4.1, ranking: 10, admissionDifficulty: "Moderate" },
    { name: "Mar Ivanios College Thiruvananthapuram", state: "Kerala", location: "Thiruvananthapuram", availableCourses: ["economics", "vis-comm", "journalism", "psychology", "biotech"], fees: "₹38,000 / year", avgPackage: "₹4.2L", highestPackage: "₹15L", placementScore: 82, website: "https://marivanioscollege.ac.in", category: "Private", rating: 4.5, ranking: 8, admissionDifficulty: "Moderate" },
    { name: "Union Christian (UC) College Aluva", state: "Kerala", location: "Aluva", availableCourses: ["psychology", "economics", "vis-comm", "env-science", "journalism"], fees: "₹35,000 / year", avgPackage: "₹3.8L", highestPackage: "₹12L", placementScore: 77, website: "https://uccollege.edu.in", category: "Private", rating: 4.3, ranking: 9, admissionDifficulty: "Low" },
    { name: "St. Joseph's College Devagiri, Kozhikode", state: "Kerala", location: "Kozhikode", availableCourses: ["psychology", "economics", "vis-comm", "digital-media", "journalism"], fees: "₹35,000 / year", avgPackage: "₹4.0L", highestPackage: "₹14L", placementScore: 80, website: "https://devagiricollege.org", category: "Private", rating: 4.4, ranking: 11, admissionDifficulty: "Moderate" },
    { name: "Assumption College Changanassery", state: "Kerala", location: "Changanassery", availableCourses: ["fashion-design", "textile-design", "economics", "psychology", "social-work"], fees: "₹38,000 / year", avgPackage: "₹3.6L", highestPackage: "₹11L", placementScore: 76, website: "https://assumptioncollege.edu.in", category: "Private", rating: 4.2, ranking: 12, admissionDifficulty: "Low" },
    { name: "CMS College Kottayam", state: "Kerala", location: "Kottayam", availableCourses: ["economics", "vis-comm", "biotech", "env-science", "psychology"], fees: "₹35,000 / year", avgPackage: "₹4L", highestPackage: "₹11L", placementScore: 75, website: "https://www.cmscollege.ac.in", category: "Private", rating: 4.3, ranking: 13, admissionDifficulty: "Moderate" },
    { name: "Don Bosco College Mannuthy", state: "Kerala", location: "Thrissur", availableCourses: ["bba", "digital-marketing", "vis-comm", "journalism"], fees: "₹40,000 / year", avgPackage: "₹3.8L", highestPackage: "₹11L", placementScore: 76, website: "https://www.donboscomannuthy.in", category: "Private", rating: 4.1, ranking: 14, admissionDifficulty: "Low" },
    { name: "Chinmaya Arts & Science College", state: "Kerala", location: "Thrissur", availableCourses: ["bba", "economics", "psychology", "teaching"], fees: "₹34,000 / year", avgPackage: "₹3.5L", highestPackage: "₹10L", placementScore: 73, website: "https://www.chinmayacollege.ac.in", category: "Private", rating: 4.0, ranking: 15, admissionDifficulty: "Low" },

    // ─── DESIGN & MEDIA ───────────────────────────────────────────────────
    { name: "ICAT Design and Media College Kochi", state: "Kerala", location: "Kochi", availableCourses: ["ui-ux", "animation", "graphic-design", "game-dev", "vis-comm", "game-art", "digital-media"], fees: "₹1.8L / year", avgPackage: "₹4.5L", highestPackage: "₹15L", placementScore: 82, website: "https://www.icat.ac.in", category: "Private", rating: 4.1, ranking: 1, admissionDifficulty: "Moderate" },
    { name: "NIFT Kannur", state: "Kerala", location: "Kannur", availableCourses: ["fashion-design", "graphic-design", "vis-comm", "textile-design", "fashion-marketing", "fashion-styling"], fees: "₹2.8L / year", avgPackage: "₹5.5L", highestPackage: "₹18L", placementScore: 84, website: "https://www.nift.ac.in/kannur", category: "Government", rating: 4.3, ranking: 3, admissionDifficulty: "High" },
    { name: "Government College of Fine Arts Thrissur", state: "Kerala", location: "Thrissur", availableCourses: ["graphic-design", "vis-comm", "interior-design", "web-design", "animation"], fees: "₹12,000 / year", avgPackage: "₹3L", highestPackage: "₹8L", placementScore: 68, website: "https://www.artscollege.in", category: "Government", rating: 4.0, ranking: 5, admissionDifficulty: "Moderate" },
    { name: "Kerala Media Academy", state: "Kerala", location: "Thiruvananthapuram", availableCourses: ["journalism", "media-prod", "digital-media", "filmmaking", "vis-comm"], fees: "₹50,000 / year", avgPackage: "₹3.5L", highestPackage: "₹12L", placementScore: 75, website: "https://www.keralamediaacademy.org", category: "Government", rating: 4.2, ranking: 1, admissionDifficulty: "Moderate" },
    { name: "MES College Marampally (Arts & Design)", state: "Kerala", location: "Aluva", availableCourses: ["vis-comm", "animation", "fashion-design", "digital-marketing", "fashion-styling"], fees: "₹40,000 / year", avgPackage: "₹3.8L", highestPackage: "₹12L", placementScore: 78, website: "https://www.mesmarampally.org", category: "Private", rating: 4.1, ranking: 4, admissionDifficulty: "Low" },

    // ─── HEALTHCARE & MEDICAL ─────────────────────────────────────────────
    { name: "Amrita Institute of Medical Sciences", state: "Kerala", location: "Kochi", availableCourses: ["nursing", "physiotherapy", "pharmacy", "biomedical-eng", "hospital-admin", "nutrition-diet"], fees: "₹2.2L / year", avgPackage: "₹5.5L", highestPackage: "₹18L", placementScore: 90, website: "https://www.amrita.edu", category: "Private", rating: 4.6, ranking: 1, admissionDifficulty: "Very High" },
    { name: "Govt Medical College Kozhikode", state: "Kerala", location: "Kozhikode", availableCourses: ["nursing", "physiotherapy", "pharmacy", "hospital-admin", "nutrition-diet"], fees: "₹22,000 / year", avgPackage: "₹6L", highestPackage: "₹15L", placementScore: 88, website: "https://www.govtmedicalcollegecalicut.ac.in", category: "Government", rating: 4.7, ranking: 2, admissionDifficulty: "Extremely High" },
    { name: "KIMS College of Nursing", state: "Kerala", location: "Thiruvananthapuram", availableCourses: ["nursing", "physiotherapy", "hospital-admin"], fees: "₹1.5L / year", avgPackage: "₹4.2L", highestPackage: "₹10L", placementScore: 83, website: "https://kimshealth.org", category: "Private", rating: 4.3, ranking: 3, admissionDifficulty: "Moderate" },
    { name: "National Institute of Speech and Hearing (NISH)", state: "Kerala", location: "Thiruvananthapuram", availableCourses: ["psychology", "teaching", "special-edu", "counseling-psych"], fees: "₹25,000 / year", avgPackage: "₹3.5L", highestPackage: "₹8L", placementScore: 81, website: "https://www.nish.ac.in", category: "Government", rating: 4.5, ranking: 4, admissionDifficulty: "Moderate" },
    { name: "Rajagiri College of Social Sciences", state: "Kerala", location: "Kochi", availableCourses: ["psychology", "clinical-psychology", "social-work", "bba", "hrm", "org-behavior", "counseling-psych"], fees: "₹80,000 / year", avgPackage: "₹4.8L", highestPackage: "₹16L", placementScore: 84, website: "https://www.rajagiri.edu", category: "Private", rating: 4.5, ranking: 5, admissionDifficulty: "Moderate" },

    // ─── AGRICULTURE ──────────────────────────────────────────────────────
    { name: "Kerala Agricultural University (KAU)", state: "Kerala", location: "Thrissur", availableCourses: ["agriculture", "biotech", "food-tech", "vet-science", "env-science", "agritech-farming", "horticulture"], fees: "₹28,000 / year", avgPackage: "₹4.5L", highestPackage: "₹14L", placementScore: 80, website: "https://www.kau.in", category: "Government", rating: 4.4, ranking: 1, admissionDifficulty: "High" },
    { name: "Kerala Veterinary and Animal Sciences University", state: "Kerala", location: "Wayanad", availableCourses: ["vet-science", "food-tech", "nutrition-diet"], fees: "₹40,000 / year", avgPackage: "₹5L", highestPackage: "₹12L", placementScore: 82, website: "https://www.kvasu.ac.in", category: "Government", rating: 4.4, ranking: 2, admissionDifficulty: "High" },
    { name: "Kerala University of Fisheries and Ocean Studies (KUFOS)", state: "Kerala", location: "Kochi", availableCourses: ["env-science", "food-tech", "biotech", "marine-eng"], fees: "₹30,000 / year", avgPackage: "₹4L", highestPackage: "₹10L", placementScore: 80, website: "http://www.kufos.ac.in", category: "Government", rating: 4.3, ranking: 3, admissionDifficulty: "Moderate" },

    // ─── LAW ─────────────────────────────────────────────────────────────
    { name: "Government Law College Ernakulam", state: "Kerala", location: "Ernakulam", availableCourses: ["law", "criminology", "cyber-law", "corporate-law"], fees: "₹8,000 / year", avgPackage: "₹5L", highestPackage: "₹18L", placementScore: 78, website: "https://glcerakulam.ac.in", category: "Government", rating: 4.3, ranking: 1, admissionDifficulty: "High" },
    { name: "Government Law College Thiruvananthapuram", state: "Kerala", location: "Thiruvananthapuram", availableCourses: ["law", "intl-law", "corporate-law"], fees: "₹8,000 / year", avgPackage: "₹4.8L", highestPackage: "₹16L", placementScore: 79, website: "https://glctvpm.tvpm.org", category: "Government", rating: 4.2, ranking: 2, admissionDifficulty: "High" },
    { name: "LISSAH Kozhikode", state: "Kerala", location: "Kozhikode", availableCourses: ["law", "corporate-law", "cyber-law"], fees: "₹55,000 / year", avgPackage: "₹4.5L", highestPackage: "₹14L", placementScore: 76, website: "https://www.lissah.com", category: "Private", rating: 4.1, ranking: 3, admissionDifficulty: "Moderate" },

    // ─── AVIATION & HOSPITALITY ───────────────────────────────────────────
    { name: "IHM Kovalam (Institute of Hotel Management)", state: "Kerala", location: "Thiruvananthapuram", availableCourses: ["hotel-mgmt", "culinary-arts", "hospitality-mgmt", "spa-wellness", "travel-tourism"], fees: "₹1.2L / year", avgPackage: "₹4.8L", highestPackage: "₹14L", placementScore: 85, website: "https://www.ihmkodalam.com", category: "Government", rating: 4.4, ranking: 1, admissionDifficulty: "Moderate" },
    { name: "Oriental School of Hotel Management", state: "Kerala", location: "Wayanad", availableCourses: ["hotel-mgmt", "culinary-arts", "travel-tourism", "spa-wellness"], fees: "₹1.1L / year", avgPackage: "₹4.2L", highestPackage: "₹12L", placementScore: 81, website: "https://www.orientalschool.co.in", category: "Private", rating: 4.2, ranking: 2, admissionDifficulty: "Moderate" },
    { name: "Mount Zion College of Aviation", state: "Kerala", location: "Pathanamthitta", availableCourses: ["aviation", "cabin-crew", "aerospace-mgmt"], fees: "₹1.5L / year", avgPackage: "₹4.5L", highestPackage: "₹12L", placementScore: 78, website: "https://mountzionaviation.com", category: "Private", rating: 4.1, ranking: 1, admissionDifficulty: "Moderate" },

    // ─── ADDITIONAL ARTS & SCIENCE ────────────────────────────────────────
    { name: "Kristu Jyoti College of Management and Technology", state: "Kerala", location: "Changanassery", availableCourses: ["bba", "finance-path", "graphic-design", "vis-comm", "digital-marketing", "seo-content"], fees: "₹45,000 / year", avgPackage: "₹3.8L", highestPackage: "₹10L", placementScore: 78, website: "https://www.kristujyoticollege.org", category: "Private", rating: 4.2, ranking: 16, admissionDifficulty: "Low" },
    { name: "MES Nedumkandam College", state: "Kerala", location: "Idukki", availableCourses: ["bba", "travel-tourism", "economics", "digital-marketing"], fees: "₹32,000 / year", avgPackage: "₹3.2L", highestPackage: "₹8L", placementScore: 72, website: "https://mesnedumkandam.org", category: "Private", rating: 4.0, ranking: 17, admissionDifficulty: "Low" },
    { name: "MACFAST - Mar Augusthinose College", state: "Kerala", location: "Ramapuram", availableCourses: ["psychology", "economics", "vis-comm", "biotech"], fees: "₹35,000 / year", avgPackage: "₹3.6L", highestPackage: "₹10L", placementScore: 74, website: "https://www.macfast.org", category: "Private", rating: 4.0, ranking: 18, admissionDifficulty: "Low" },
    { name: "Calicut University (University of Calicut Campus)", state: "Kerala", location: "Malappuram", availableCourses: ["bba", "economics", "psychology", "law", "journalism", "social-work", "teaching"], fees: "₹20,000 / year", avgPackage: "₹3.8L", highestPackage: "₹14L", placementScore: 75, website: "https://www.uoc.ac.in", category: "Government", rating: 4.3, ranking: 2, admissionDifficulty: "Moderate" },
    { name: "MG University (Mahatma Gandhi University)", state: "Kerala", location: "Kottayam", availableCourses: ["bba", "economics", "biotech", "law", "journalism", "teaching", "social-work"], fees: "₹18,000 / year", avgPackage: "₹3.5L", highestPackage: "₹12L", placementScore: 73, website: "https://www.mguniversity.in", category: "Government", rating: 4.2, ranking: 3, admissionDifficulty: "Moderate" },
    { name: "Kerala University (Trivandrum Campus)", state: "Kerala", location: "Thiruvananthapuram", availableCourses: ["bba", "economics", "law", "journalism", "psychology", "teaching", "social-work"], fees: "₹18,000 / year", avgPackage: "₹3.6L", highestPackage: "₹12L", placementScore: 74, website: "https://www.keralauniversity.ac.in", category: "Government", rating: 4.2, ranking: 4, admissionDifficulty: "Moderate" },
    { name: "Kannur University", state: "Kerala", location: "Kannur", availableCourses: ["economics", "journalism", "law", "psychology", "social-work"], fees: "₹16,000 / year", avgPackage: "₹3.3L", highestPackage: "₹10L", placementScore: 70, website: "https://www.kannuruniversity.ac.in", category: "Government", rating: 4.1, ranking: 5, admissionDifficulty: "Moderate" }
  ],

  india: [
    // ─── IITs ─────────────────────────────────────────────────────────────
    { name: "IIT Bombay (IITB)", state: "Maharashtra", location: "Mumbai", availableCourses: ["btech-cse", "ai-ml", "robotics", "machine-learning", "product-design", "renewable-energy", "robot-vision", "data-science"], fees: "₹2.2L / year", avgPackage: "₹23L", highestPackage: "₹2.1Cr", placementScore: 99, website: "https://www.iitb.ac.in", category: "Government", rating: 4.9, ranking: 1, admissionDifficulty: "Extremely High" },
    { name: "IIT Delhi (IITD)", state: "Delhi", location: "New Delhi", availableCourses: ["btech-cse", "ai-ml", "robotics", "machine-learning", "renewable-energy", "iot-engineering", "data-science"], fees: "₹2.2L / year", avgPackage: "₹22L", highestPackage: "₹1.8Cr", placementScore: 99, website: "https://www.iitd.ac.in", category: "Government", rating: 4.9, ranking: 2, admissionDifficulty: "Extremely High" },
    { name: "IIT Madras (IITM)", state: "Tamil Nadu", location: "Chennai", availableCourses: ["btech-cse", "ai-ml", "robotics", "renewable-energy", "iot-engineering", "data-science", "machine-learning"], fees: "₹2.2L / year", avgPackage: "₹21L", highestPackage: "₹1.6Cr", placementScore: 99, website: "https://www.iitm.ac.in", category: "Government", rating: 4.9, ranking: 3, admissionDifficulty: "Extremely High" },
    { name: "IIT Kharagpur (IITKGP)", state: "West Bengal", location: "Kharagpur", availableCourses: ["btech-cse", "ai-ml", "biotech", "renewable-energy", "marine-eng", "architecture"], fees: "₹2.2L / year", avgPackage: "₹19.5L", highestPackage: "₹1.5Cr", placementScore: 98, website: "https://www.iitkgp.ac.in", category: "Government", rating: 4.8, ranking: 4, admissionDifficulty: "Extremely High" },
    { name: "IIT Kanpur (IITK)", state: "Uttar Pradesh", location: "Kanpur", availableCourses: ["btech-cse", "ai-ml", "robotics", "machine-learning", "aerospace-mgmt"], fees: "₹2.2L / year", avgPackage: "₹20L", highestPackage: "₹1.7Cr", placementScore: 98, website: "https://www.iitk.ac.in", category: "Government", rating: 4.8, ranking: 5, admissionDifficulty: "Extremely High" },
    { name: "IIT Roorkee (IITR)", state: "Uttarakhand", location: "Roorkee", availableCourses: ["btech-cse", "ai-ml", "architecture", "renewable-energy", "biotechnology"], fees: "₹2.2L / year", avgPackage: "₹18L", highestPackage: "₹1.2Cr", placementScore: 97, website: "https://www.iitr.ac.in", category: "Government", rating: 4.8, ranking: 6, admissionDifficulty: "Extremely High" },
    { name: "IIT Hyderabad (IITH)", state: "Telangana", location: "Hyderabad", availableCourses: ["btech-cse", "ai-ml", "data-science", "machine-learning", "renewable-energy"], fees: "₹2.2L / year", avgPackage: "₹16L", highestPackage: "₹98L", placementScore: 96, website: "https://www.iith.ac.in", category: "Government", rating: 4.7, ranking: 7, admissionDifficulty: "Extremely High" },

    // ─── NITs ─────────────────────────────────────────────────────────────
    { name: "NIT Trichy (NITT)", state: "Tamil Nadu", location: "Tiruchirappalli", availableCourses: ["btech-cse", "ai-ml", "robotics", "renewable-energy", "architecture"], fees: "₹1.5L / year", avgPackage: "₹12L", highestPackage: "₹78L", placementScore: 95, website: "https://www.nitt.edu", category: "Government", rating: 4.7, ranking: 8, admissionDifficulty: "Very High" },
    { name: "NIT Surathkal (NITK)", state: "Karnataka", location: "Surathkal", availableCourses: ["btech-cse", "ai-ml", "marine-eng", "iot-engineering"], fees: "₹1.5L / year", avgPackage: "₹11L", highestPackage: "₹65L", placementScore: 94, website: "https://www.nitk.ac.in", category: "Government", rating: 4.6, ranking: 9, admissionDifficulty: "Very High" },

    // ─── IIITs ────────────────────────────────────────────────────────────
    { name: "IIIT Hyderabad (IIITH)", state: "Telangana", location: "Hyderabad", availableCourses: ["btech-cse", "ai-ml", "machine-learning", "nlp-specialist", "robot-vision", "data-science"], fees: "₹3L / year", avgPackage: "₹20L", highestPackage: "₹1.2Cr", placementScore: 98, website: "https://www.iiit.ac.in", category: "Private", rating: 4.8, ranking: 10, admissionDifficulty: "Extremely High" },
    { name: "IIIT Bangalore (IIITB)", state: "Karnataka", location: "Bengaluru", availableCourses: ["btech-cse", "ai-ml", "machine-learning", "data-science", "software-testing"], fees: "₹6L / year", avgPackage: "₹18L", highestPackage: "₹80L", placementScore: 96, website: "https://www.iiitb.ac.in", category: "Private", rating: 4.7, ranking: 11, admissionDifficulty: "Very High" },

    // ─── TOP ENGINEERING PRIVATE ──────────────────────────────────────────
    { name: "BITS Pilani", state: "Rajasthan", location: "Pilani", availableCourses: ["btech-cse", "ai-ml", "cloud-computing", "game-dev", "biotech", "blockchain-dev", "data-science"], fees: "₹5.1L / year", avgPackage: "₹18L", highestPackage: "₹82L", placementScore: 98, website: "https://www.bits-pilani.ac.in", category: "Private", rating: 4.8, ranking: 12, admissionDifficulty: "Extremely High" },
    { name: "VIT Vellore", state: "Tamil Nadu", location: "Vellore", availableCourses: ["btech-cse", "ai-ml", "cybersecurity", "ethical-hacking", "cloud-computing", "biotech", "blockchain-dev", "data-science"], fees: "₹1.9L / year", avgPackage: "₹8.1L", highestPackage: "₹75L", placementScore: 93, website: "https://vit.ac.in", category: "Private", rating: 4.4, ranking: 13, admissionDifficulty: "Very High" },
    { name: "SRM Institute of Science and Technology", state: "Tamil Nadu", location: "Chennai", availableCourses: ["btech-cse", "cybersecurity", "ethical-hacking", "cloud-computing", "game-dev", "software-testing", "data-science"], fees: "₹2.6L / year", avgPackage: "₹7.2L", highestPackage: "₹45L", placementScore: 91, website: "https://www.srmist.edu.in", category: "Private", rating: 4.3, ranking: 14, admissionDifficulty: "High" },
    { name: "Manipal Academy of Higher Education (MAHE)", state: "Karnataka", location: "Manipal", availableCourses: ["btech-cse", "ui-ux", "animation", "graphic-design", "journalism", "vis-comm", "game-art", "hotel-mgmt"], fees: "₹3.5L / year", avgPackage: "₹8.5L", highestPackage: "₹54L", placementScore: 90, website: "https://www.manipal.edu", category: "Private", rating: 4.6, ranking: 15, admissionDifficulty: "High" },
    { name: "Delhi Technological University (DTU)", state: "Delhi", location: "New Delhi", availableCourses: ["btech-cse", "robotics", "biotech", "iot-engineering", "data-science"], fees: "₹1.9L / year", avgPackage: "₹12.5L", highestPackage: "₹64L", placementScore: 94, website: "https://www.dtu.ac.in", category: "Government", rating: 4.6, ranking: 16, admissionDifficulty: "Very High" },
    { name: "KIIT University", state: "Odisha", location: "Bhubaneswar", availableCourses: ["btech-cse", "ai-ml", "robotics", "cybersecurity", "law", "game-dev", "data-science"], fees: "₹3.5L / year", avgPackage: "₹6.5L", highestPackage: "₹40L", placementScore: 90, website: "https://kiit.ac.in", category: "Private", rating: 4.3, ranking: 17, admissionDifficulty: "Moderate" },
    { name: "Indian Institute of Science (IISc)", state: "Karnataka", location: "Bengaluru", availableCourses: ["biotech", "renewable-energy", "machine-learning", "nlp-specialist", "robot-vision"], fees: "₹30,000 / year", avgPackage: "₹20L", highestPackage: "₹85L", placementScore: 98, website: "https://iisc.ac.in", category: "Government", rating: 4.9, ranking: 18, admissionDifficulty: "Extremely High" },
    { name: "Chandigarh University", state: "Punjab", location: "Chandigarh", availableCourses: ["btech-cse", "ai-ml", "cybersecurity", "data-science", "full-stack-dev", "cloud-computing"], fees: "₹1.8L / year", avgPackage: "₹6.5L", highestPackage: "₹42L", placementScore: 88, website: "https://www.cuchd.in", category: "Private", rating: 4.2, ranking: 19, admissionDifficulty: "Moderate" },
    { name: "UPES Dehradun", state: "Uttarakhand", location: "Dehradun", availableCourses: ["btech-cse", "cybersecurity", "aviation", "aerospace-mgmt", "energy-mgmt", "iot-engineering"], fees: "₹2.4L / year", avgPackage: "₹6L", highestPackage: "₹38L", placementScore: 85, website: "https://www.upes.ac.in", category: "Private", rating: 4.2, ranking: 20, admissionDifficulty: "Moderate" },
    { name: "Lovely Professional University (LPU)", state: "Punjab", location: "Phagwara", availableCourses: ["hotel-mgmt", "culinary-arts", "agriculture", "fashion-design", "aviation", "cabin-crew", "btech-cse"], fees: "₹1.4L / year", avgPackage: "₹5.8L", highestPackage: "₹64L", placementScore: 86, website: "https://www.lpu.in", category: "Private", rating: 4.1, ranking: 21, admissionDifficulty: "Low" },

    // ─── TOP BUSINESS SCHOOLS ─────────────────────────────────────────────
    { name: "IIM Ahmedabad (IIMA)", state: "Gujarat", location: "Ahmedabad", availableCourses: ["mba-integrated", "intl-business", "supply-chain", "hrm", "family-business", "biz-analytics", "product-mgmt"], fees: "₹25L total", avgPackage: "₹34L", highestPackage: "₹1.1Cr", placementScore: 100, website: "https://www.iima.ac.in", category: "Government", rating: 5.0, ranking: 1, admissionDifficulty: "Extremely High" },
    { name: "IIM Bangalore (IIMB)", state: "Karnataka", location: "Bengaluru", availableCourses: ["mba-integrated", "intl-business", "supply-chain", "hrm", "biz-analytics", "product-mgmt", "brand-mgmt"], fees: "₹24L total", avgPackage: "₹32L", highestPackage: "₹95L", placementScore: 100, website: "https://www.iimb.ac.in", category: "Government", rating: 5.0, ranking: 2, admissionDifficulty: "Extremely High" },
    { name: "Symbiosis Institute of Business Management (SIBM)", state: "Maharashtra", location: "Pune", availableCourses: ["bba", "mba-integrated", "intl-business", "supply-chain", "hrm", "brand-mgmt", "family-business"], fees: "₹8.5L / year", avgPackage: "₹23L", highestPackage: "₹45L", placementScore: 97, website: "https://www.sibm.edu", category: "Private", rating: 4.7, ranking: 3, admissionDifficulty: "Very High" },
    { name: "NMIMS University", state: "Maharashtra", location: "Mumbai", availableCourses: ["bba", "finance-path", "ecommerce", "biz-analytics", "fintech", "law", "investment-mgmt", "brand-mgmt"], fees: "₹3.2L / year", avgPackage: "₹10.5L", highestPackage: "₹32L", placementScore: 92, website: "https://www.nmims.edu", category: "Private", rating: 4.5, ranking: 4, admissionDifficulty: "Very High" },
    { name: "Shri Ram College of Commerce (SRCC)", state: "Delhi", location: "New Delhi", availableCourses: ["finance-path", "economics", "actuarial-science", "investment-mgmt", "ca"], fees: "₹30,000 / year", avgPackage: "₹10.5L", highestPackage: "₹36L", placementScore: 96, website: "https://www.srcc.edu", category: "Government", rating: 4.8, ranking: 5, admissionDifficulty: "Extremely High" },
    { name: "ISB Hyderabad", state: "Telangana", location: "Hyderabad", availableCourses: ["mba-integrated", "biz-analytics", "intl-business", "product-mgmt", "fintech"], fees: "₹40L total", avgPackage: "₹35L", highestPackage: "₹1.2Cr", placementScore: 100, website: "https://www.isb.edu", category: "Private", rating: 4.9, ranking: 6, admissionDifficulty: "Extremely High" },
    { name: "XLRI Jamshedpur", state: "Jharkhand", location: "Jamshedpur", availableCourses: ["mba-integrated", "hrm", "biz-analytics", "brand-mgmt", "intl-business"], fees: "₹28L total", avgPackage: "₹30L", highestPackage: "₹85L", placementScore: 99, website: "https://www.xlri.ac.in", category: "Private", rating: 4.8, ranking: 7, admissionDifficulty: "Extremely High" },
    { name: "SP Jain School of Global Management", state: "Maharashtra", location: "Mumbai", availableCourses: ["mba-integrated", "biz-analytics", "intl-business", "brand-mgmt", "product-mgmt"], fees: "₹35L total", avgPackage: "₹28L", highestPackage: "₹72L", placementScore: 97, website: "https://www.spjain.org", category: "Private", rating: 4.7, ranking: 8, admissionDifficulty: "Very High" },
    { name: "Christ University Bengaluru", state: "Karnataka", location: "Bengaluru", availableCourses: ["bba", "mba-integrated", "psychology", "economics", "digital-marketing", "vis-comm", "org-behavior", "counseling-psych"], fees: "₹1.8L / year", avgPackage: "₹6.8L", highestPackage: "₹22L", placementScore: 89, website: "https://www.christuniversity.in", category: "Private", rating: 4.5, ranking: 9, admissionDifficulty: "High" },
    { name: "Amity University", state: "Uttar Pradesh", location: "Noida", availableCourses: ["fashion-design", "interior-design", "advertising", "media-prod", "clinical-psychology", "fashion-styling", "digital-marketing"], fees: "₹2.2L / year", avgPackage: "₹5.2L", highestPackage: "₹28L", placementScore: 84, website: "https://www.amity.edu", category: "Private", rating: 4.1, ranking: 10, admissionDifficulty: "Moderate" },
    { name: "Jain University", state: "Karnataka", location: "Bengaluru", availableCourses: ["sports-mgmt", "sports-science", "game-dev", "bba", "digital-marketing", "fintech", "sports-coaching", "fitness-nutrition"], fees: "₹1.6L / year", avgPackage: "₹5.5L", highestPackage: "₹30L", placementScore: 86, website: "https://www.jainuniversity.ac.in", category: "Private", rating: 4.2, ranking: 11, admissionDifficulty: "Moderate" },
    { name: "Ashoka University", state: "Haryana", location: "Sonipat", availableCourses: ["economics", "psychology", "pol-science", "vis-comm", "env-science", "ai-ethics", "social-entrepreneurship", "org-behavior"], fees: "₹7.5L / year", avgPackage: "₹9.5L", highestPackage: "₹35L", placementScore: 92, website: "https://www.ashoka.edu.in", category: "Private", rating: 4.7, ranking: 12, admissionDifficulty: "Very High" },
    { name: "Shiv Nadar University", state: "Uttar Pradesh", location: "Greater Noida", availableCourses: ["btech-cse", "economics", "env-science", "biotech", "data-science", "machine-learning"], fees: "₹3.5L / year", avgPackage: "₹7.8L", highestPackage: "₹29L", placementScore: 88, website: "https://snu.edu.in", category: "Private", rating: 4.4, ranking: 13, admissionDifficulty: "High" },
    { name: "OP Jindal Global University", state: "Haryana", location: "Sonipat", availableCourses: ["law", "corporate-law", "intl-law", "economics", "pol-science", "intl-business", "journalism"], fees: "₹4.5L / year", avgPackage: "₹12L", highestPackage: "₹48L", placementScore: 91, website: "https://jgu.edu.in", category: "Private", rating: 4.6, ranking: 14, admissionDifficulty: "High" },

    // ─── DESIGN & FASHION ────────────────────────────────────────────────
    { name: "National Institute of Design (NID) Ahmedabad", state: "Gujarat", location: "Ahmedabad", availableCourses: ["ui-ux", "product-design", "graphic-design", "animation", "vis-comm", "web-design", "game-art", "interior-design"], fees: "₹2.1L / year", avgPackage: "₹12L", highestPackage: "₹36L", placementScore: 94, website: "https://www.nid.edu", category: "Government", rating: 4.8, ranking: 1, admissionDifficulty: "Extremely High" },
    { name: "National Institute of Fashion Technology (NIFT) Delhi", state: "Delhi", location: "New Delhi", availableCourses: ["fashion-design", "graphic-design", "vis-comm", "textile-design", "fashion-marketing", "fashion-styling"], fees: "₹2.8L / year", avgPackage: "₹7.5L", highestPackage: "₹22L", placementScore: 88, website: "https://www.nift.ac.in", category: "Government", rating: 4.6, ranking: 2, admissionDifficulty: "Very High" },
    { name: "Pearl Academy", state: "Delhi", location: "New Delhi", availableCourses: ["fashion-design", "ui-ux", "graphic-design", "interior-design", "fashion-styling", "fashion-marketing"], fees: "₹4.5L / year", avgPackage: "₹5.5L", highestPackage: "₹18L", placementScore: 85, website: "https://www.pearlacademy.com", category: "Private", rating: 4.4, ranking: 3, admissionDifficulty: "High" },
    { name: "Srishti Manipal Institute of Art, Design & Technology", state: "Karnataka", location: "Bengaluru", availableCourses: ["ui-ux", "product-design", "graphic-design", "animation", "game-art", "interior-design", "filmmaking"], fees: "₹5.5L / year", avgPackage: "₹6.8L", highestPackage: "₹18L", placementScore: 86, website: "https://srishtimanipalinstitute.in", category: "Private", rating: 4.5, ranking: 4, admissionDifficulty: "High" },

    // ─── LAW SCHOOLS ─────────────────────────────────────────────────────
    { name: "National Law School of India University (NLSIU)", state: "Karnataka", location: "Bengaluru", availableCourses: ["law", "criminology", "cyber-law", "intl-law", "corporate-law"], fees: "₹2.5L / year", avgPackage: "₹16L", highestPackage: "₹96L", placementScore: 98, website: "https://www.nls.ac.in", category: "Government", rating: 4.9, ranking: 1, admissionDifficulty: "Extremely High" },
    { name: "NALSAR University of Law", state: "Telangana", location: "Hyderabad", availableCourses: ["law", "cyber-law", "intl-law", "corporate-law"], fees: "₹2.6L / year", avgPackage: "₹15L", highestPackage: "₹80L", placementScore: 97, website: "https://www.nalsar.ac.in", category: "Government", rating: 4.8, ranking: 2, admissionDifficulty: "Extremely High" },
    { name: "National Law University, Delhi", state: "Delhi", location: "New Delhi", availableCourses: ["law", "cyber-law", "intl-law", "corporate-law", "criminology"], fees: "₹2.7L / year", avgPackage: "₹15.5L", highestPackage: "₹82L", placementScore: 98, website: "https://nludelhi.ac.in", category: "Government", rating: 4.8, ranking: 3, admissionDifficulty: "Extremely High" },
    { name: "Symbiosis Law School Pune", state: "Maharashtra", location: "Pune", availableCourses: ["law", "criminology", "intl-law", "corporate-law", "cyber-law"], fees: "₹3.8L / year", avgPackage: "₹8.5L", highestPackage: "₹25L", placementScore: 90, website: "https://www.symbiosislaw.ac.in", category: "Private", rating: 4.5, ranking: 4, admissionDifficulty: "High" },
    { name: "Alliance University Bengaluru", state: "Karnataka", location: "Bengaluru", availableCourses: ["law", "bba", "finance-path", "intl-business", "supply-chain", "cyber-law", "corporate-law"], fees: "₹2.8L / year", avgPackage: "₹6.8L", highestPackage: "₹26L", placementScore: 87, website: "https://www.alliance.edu.in", category: "Private", rating: 4.2, ranking: 5, admissionDifficulty: "Moderate" },

    // ─── HEALTHCARE & MEDICAL ─────────────────────────────────────────────
    { name: "AIIMS Delhi", state: "Delhi", location: "New Delhi", availableCourses: ["nursing", "biomedical-eng", "hospital-admin", "biotech", "pharmacy"], fees: "₹1,500 / year", avgPackage: "₹14L", highestPackage: "₹48L", placementScore: 100, website: "https://www.aiims.edu", category: "Government", rating: 5.0, ranking: 1, admissionDifficulty: "Extremely High" },
    { name: "Christian Medical College (CMC) Vellore", state: "Tamil Nadu", location: "Vellore", availableCourses: ["nursing", "physiotherapy", "pharmacy", "nutrition-diet", "hospital-admin"], fees: "₹45,000 / year", avgPackage: "₹6L", highestPackage: "₹18L", placementScore: 97, website: "https://www.cmcvellore.ac.in", category: "Private", rating: 4.8, ranking: 2, admissionDifficulty: "Extremely High" },
    { name: "Armed Forces Medical College (AFMC) Pune", state: "Maharashtra", location: "Pune", availableCourses: ["nursing", "hospital-admin", "disaster-mgmt", "biomedical-eng"], fees: "₹25,000 / year", avgPackage: "₹12L", highestPackage: "₹24L", placementScore: 99, website: "https://www.afmc.nic.in", category: "Government", rating: 4.9, ranking: 3, admissionDifficulty: "Extremely High" },
    { name: "National Institute of Pharmaceutical Education & Research (NIPER)", state: "Punjab", location: "Mohali", availableCourses: ["pharmacy", "nutrition-diet", "biotech"], fees: "₹1.2L / year", avgPackage: "₹7.5L", highestPackage: "₹20L", placementScore: 96, website: "http://www.niper.gov.in", category: "Government", rating: 4.7, ranking: 4, admissionDifficulty: "Very High" },

    // ─── MEDIA & COMMUNICATION ────────────────────────────────────────────
    { name: "Whistling Woods International", state: "Maharashtra", location: "Mumbai", availableCourses: ["filmmaking", "media-prod", "animation", "audio-engineering", "digital-media", "vis-comm"], fees: "₹7.5L / year", avgPackage: "₹6.5L", highestPackage: "₹32L", placementScore: 85, website: "https://www.whistlingwoods.net", category: "Private", rating: 4.6, ranking: 1, admissionDifficulty: "High" },
    { name: "Symbiosis Centre for Media & Communication (SCMC)", state: "Maharashtra", location: "Pune", availableCourses: ["journalism", "vis-comm", "media-prod", "digital-media", "advertising"], fees: "₹3.2L / year", avgPackage: "₹5.8L", highestPackage: "₹15L", placementScore: 88, website: "https://www.scmc.edu.in", category: "Private", rating: 4.4, ranking: 2, admissionDifficulty: "High" },
    { name: "Flame University", state: "Maharashtra", location: "Pune", availableCourses: ["economics", "psychology", "advertising", "vis-comm", "bba", "digital-media", "org-behavior"], fees: "₹7.2L / year", avgPackage: "₹7.5L", highestPackage: "₹22L", placementScore: 88, website: "https://www.flame.edu.in", category: "Private", rating: 4.4, ranking: 3, admissionDifficulty: "High" },
    { name: "Loyola College Chennai", state: "Tamil Nadu", location: "Chennai", availableCourses: ["economics", "vis-comm", "media-prod", "psychology", "digital-media", "journalism"], fees: "₹45,000 / year", avgPackage: "₹5.8L", highestPackage: "₹18L", placementScore: 89, website: "https://www.loyolacollege.edu", category: "Private", rating: 4.6, ranking: 4, admissionDifficulty: "High" },
    { name: "St. Xavier's College Mumbai", state: "Maharashtra", location: "Mumbai", availableCourses: ["vis-comm", "economics", "psychology", "digital-media", "journalism", "social-work"], fees: "₹15,000 / year", avgPackage: "₹6.2L", highestPackage: "₹24L", placementScore: 88, website: "https://xaviers.edu", category: "Private", rating: 4.6, ranking: 5, admissionDifficulty: "Very High" },
    { name: "Miranda House (Delhi University)", state: "Delhi", location: "New Delhi", availableCourses: ["economics", "psychology", "pol-science", "teaching", "social-work", "journalism"], fees: "₹24,000 / year", avgPackage: "₹7.8L", highestPackage: "₹25L", placementScore: 90, website: "https://www.mirandahouse.ac.in", category: "Government", rating: 4.8, ranking: 6, admissionDifficulty: "Extremely High" },
    { name: "Hansraj College (Delhi University)", state: "Delhi", location: "New Delhi", availableCourses: ["economics", "psychology", "pol-science", "journalism"], fees: "₹20,000 / year", avgPackage: "₹6.5L", highestPackage: "₹20L", placementScore: 86, website: "https://www.hansrajcollege.ac.in", category: "Government", rating: 4.5, ranking: 7, admissionDifficulty: "Very High" },
    { name: "St. Stephen's College Delhi", state: "Delhi", location: "New Delhi", availableCourses: ["economics", "pol-science", "social-work", "journalism"], fees: "₹40,000 / year", avgPackage: "₹8.4L", highestPackage: "₹28L", placementScore: 92, website: "https://www.ststephens.edu", category: "Private", rating: 4.7, ranking: 8, admissionDifficulty: "Extremely High" },

    // ─── AGRICULTURE, GOVT, SOCIAL SCIENCES ──────────────────────────────
    { name: "Banaras Hindu University (BHU)", state: "Uttar Pradesh", location: "Varanasi", availableCourses: ["agriculture", "horticulture", "economics", "teaching", "special-edu", "law", "journalism"], fees: "₹10,000 / year", avgPackage: "₹5.5L", highestPackage: "₹18L", placementScore: 83, website: "https://www.bhu.ac.in", category: "Government", rating: 4.6, ranking: 9, admissionDifficulty: "High" },
    { name: "Aligarh Muslim University (AMU)", state: "Uttar Pradesh", location: "Aligarh", availableCourses: ["law", "economics", "agriculture", "teaching", "engineering"], fees: "₹12,000 / year", avgPackage: "₹5.0L", highestPackage: "₹16L", placementScore: 81, website: "https://www.amu.ac.in", category: "Government", rating: 4.3, ranking: 10, admissionDifficulty: "High" },
    { name: "Tata Institute of Social Sciences (TISS)", state: "Maharashtra", location: "Mumbai", availableCourses: ["social-work", "hrm", "public-admin", "env-science", "social-entrepreneurship", "counseling-psych"], fees: "₹1.2L total", avgPackage: "₹19.5L", highestPackage: "₹42L", placementScore: 98, website: "https://www.tiss.edu", category: "Government", rating: 4.8, ranking: 11, admissionDifficulty: "Very High" },
    { name: "Jawaharlal Nehru University (JNU)", state: "Delhi", location: "New Delhi", availableCourses: ["pol-science", "economics", "intl-law", "social-work", "env-science", "journalism"], fees: "₹600 / year", avgPackage: "₹7L", highestPackage: "₹25L", placementScore: 85, website: "https://www.jnu.ac.in", category: "Government", rating: 4.7, ranking: 12, admissionDifficulty: "Very High" },
    { name: "Jamia Millia Islamia", state: "Delhi", location: "New Delhi", availableCourses: ["journalism", "architecture", "law", "economics", "social-work", "pol-science"], fees: "₹15,000 / year", avgPackage: "₹5.5L", highestPackage: "₹18L", placementScore: 82, website: "https://www.jmi.ac.in", category: "Government", rating: 4.4, ranking: 13, admissionDifficulty: "High" },
    { name: "ICFAI University", state: "Telangana", location: "Hyderabad", availableCourses: ["bba", "finance-path", "law", "biz-analytics", "banking-finance", "fintech"], fees: "₹2.5L / year", avgPackage: "₹5.5L", highestPackage: "₹22L", placementScore: 82, website: "https://www.icfai.org", category: "Private", rating: 4.1, ranking: 14, admissionDifficulty: "Moderate" },

    // ─── HOSPITALITY & AVIATION ───────────────────────────────────────────
    { name: "Institute of Hotel Management (IHM Pusa)", state: "Delhi", location: "New Delhi", availableCourses: ["hotel-mgmt", "culinary-arts", "hospitality-mgmt", "spa-wellness", "travel-tourism"], fees: "₹1.5L / year", avgPackage: "₹5L", highestPackage: "₹12L", placementScore: 92, website: "http://ihmpusa.net", category: "Government", rating: 4.6, ranking: 1, admissionDifficulty: "High" },
    { name: "Institute of Hotel Management Mumbai", state: "Maharashtra", location: "Mumbai", availableCourses: ["hotel-mgmt", "culinary-arts", "hospitality-mgmt", "spa-wellness"], fees: "₹1.4L / year", avgPackage: "₹5.2L", highestPackage: "₹14L", placementScore: 91, website: "https://www.ihmctan.edu", category: "Government", rating: 4.5, ranking: 2, admissionDifficulty: "High" },
    { name: "Indira Gandhi Rashtriya Uran Akademi (IGRUA)", state: "Uttar Pradesh", location: "Amethi", availableCourses: ["pilot", "atc"], fees: "₹45L total", avgPackage: "₹15L", highestPackage: "₹50L", placementScore: 95, website: "https://igrua.gov.in", category: "Government", rating: 4.6, ranking: 1, admissionDifficulty: "Very High" },
    { name: "Rajiv Gandhi National Aviation University (RGNAU)", state: "Uttar Pradesh", location: "Amethi", availableCourses: ["aviation", "aerospace-mgmt", "atc", "cabin-crew"], fees: "₹1.1L / year", avgPackage: "₹6L", highestPackage: "₹15L", placementScore: 86, website: "http://www.rgnau.ac.in", category: "Government", rating: 4.3, ranking: 2, admissionDifficulty: "High" },

    // ─── TRADE & INTERNATIONAL ────────────────────────────────────────────
    { name: "Indian Institute of Foreign Trade (IIFT)", state: "Delhi", location: "New Delhi", availableCourses: ["intl-business", "supply-chain", "biz-analytics", "ecommerce"], fees: "₹8L / year", avgPackage: "₹25L", highestPackage: "₹60L", placementScore: 97, website: "https://www.iift.ac.in", category: "Government", rating: 4.7, ranking: 1, admissionDifficulty: "Extremely High" },
    { name: "Welingkar Institute of Management (WeSchool)", state: "Maharashtra", location: "Mumbai", availableCourses: ["bba", "retail-mgmt", "supply-chain", "biz-analytics", "ecommerce", "digital-marketing"], fees: "₹6.5L / year", avgPackage: "₹10L", highestPackage: "₹24L", placementScore: 89, website: "https://www.welingkar.org", category: "Private", rating: 4.3, ranking: 2, admissionDifficulty: "High" }
  ]
};
