export const careerDatabase = [
  // ─── TECHNOLOGY ───────────────────────────────────────────────────────────
  { id: "btech-cse", title: "BTech Computer Science Engineering", category: "Technology", interests: ["Technology", "AI"], futureScope: "Very High", aiRisk: "Low", salary: "₹6L – ₹35L / year", startupPotential: "Excellent", globalDemand: "Very High", workLifeBalance: "Moderate", personalityMatch: ["analytical", "logical thinking", "technical interest"], streams: ["Science", "Computer Science"], skills: ["Programming", "Data Structures", "Algorithms", "System Design"], admissionExams: ["JEE Main", "KEAM", "KCET"], learningPlatforms: ["Coursera", "NPTEL", "LeetCode"] },
  { id: "ai-ml", title: "BTech Artificial Intelligence & Machine Learning", category: "AI", interests: ["AI", "Technology"], futureScope: "Extremely High", aiRisk: "Very Low", salary: "₹8L – ₹40L / year", startupPotential: "Outstanding", globalDemand: "Very High", workLifeBalance: "Moderate", personalityMatch: ["logical thinking", "innovation", "technical interest"], streams: ["Science", "Computer Science"], skills: ["Python", "Deep Learning", "NLP", "Statistics"], admissionExams: ["JEE Main", "KEAM"], learningPlatforms: ["Coursera", "fast.ai", "Google AI"] },
  { id: "robotics", title: "Robotics Engineering", category: "Technology", interests: ["Technology", "AI"], futureScope: "High", aiRisk: "Low", salary: "₹7L – ₹30L / year", startupPotential: "Good", globalDemand: "High", workLifeBalance: "Moderate", personalityMatch: ["logical thinking", "creativity", "technical interest"], streams: ["Science", "Computer Science"], skills: ["ROS", "Embedded Systems", "Control Systems", "CAD"], admissionExams: ["JEE Main", "KEAM"], learningPlatforms: ["Coursera", "ROS.org", "MIT OpenCourseWare"] },
  { id: "data-science", title: "BSc / BTech Data Science", category: "Technology", interests: ["Technology", "AI", "Finance"], futureScope: "Very High", aiRisk: "Low", salary: "₹6L – ₹28L / year", startupPotential: "Good", globalDemand: "Very High", workLifeBalance: "Good", personalityMatch: ["analytical thinking", "logical thinking", "discipline"], streams: ["Science", "Computer Science", "Commerce"], skills: ["Python", "SQL", "Visualization", "Statistics"], admissionExams: ["JEE Main", "CUCET"], learningPlatforms: ["Kaggle", "DataCamp", "Coursera"] },
  { id: "cybersecurity", title: "Cybersecurity & Information Security", category: "Technology", interests: ["Technology", "Government Jobs"], futureScope: "Very High", aiRisk: "Very Low", salary: "₹8L – ₹35L / year", startupPotential: "Excellent", globalDemand: "Very High", workLifeBalance: "Moderate", personalityMatch: ["analytical thinking", "risk tolerance", "technical interest"], streams: ["Science", "Computer Science"], skills: ["Network Security", "Cryptography", "Penetration Testing", "SIEM"], admissionExams: ["JEE Main", "KEAM"], learningPlatforms: ["TryHackMe", "HackTheBox", "Coursera"] },
  { id: "ethical-hacking", title: "Ethical Hacking & Cyber Forensics", category: "Technology", interests: ["Technology"], futureScope: "High", aiRisk: "Very Low", salary: "₹6L – ₹30L / year", startupPotential: "Good", globalDemand: "High", workLifeBalance: "Moderate", personalityMatch: ["logical thinking", "risk tolerance", "technical interest"], streams: ["Science", "Computer Science"], skills: ["Kali Linux", "OSINT", "Digital Forensics", "Exploit Dev"], admissionExams: ["JEE Main", "CEH Exam"], learningPlatforms: ["TryHackMe", "HackTheBox", "Cybrary"] },
  { id: "cloud-computing", title: "Cloud Computing & DevOps", category: "Technology", interests: ["Technology", "Business"], futureScope: "Very High", aiRisk: "Low", salary: "₹7L – ₹32L / year", startupPotential: "Good", globalDemand: "Very High", workLifeBalance: "Good", personalityMatch: ["logical thinking", "discipline", "technical interest"], streams: ["Science", "Computer Science"], skills: ["AWS", "Docker", "Kubernetes", "CI/CD"], admissionExams: ["JEE Main", "KEAM"], learningPlatforms: ["AWS Training", "Google Cloud", "Linux Foundation"] },
  { id: "game-dev", title: "BTech / BSc Game Development", category: "Technology", interests: ["Technology", "Design", "Media"], futureScope: "Very High", aiRisk: "Low", salary: "₹5L – ₹28L / year", startupPotential: "Excellent", globalDemand: "Very High", workLifeBalance: "Moderate", personalityMatch: ["creativity", "logical thinking", "technical interest"], streams: ["Computer Science", "Science"], skills: ["Unity", "Unreal Engine", "C#", "3D Modeling"], admissionExams: ["JEE Main", "NID", "NIFT"], learningPlatforms: ["Unity Learn", "Udemy", "Coursera"] },
  { id: "software-testing", title: "BSc / BTech Software QA & Testing", category: "Technology", interests: ["Technology"], futureScope: "High", aiRisk: "Moderate", salary: "₹4L – ₹18L / year", startupPotential: "Good", globalDemand: "High", workLifeBalance: "Good", personalityMatch: ["analytical", "discipline", "logical thinking"], streams: ["Computer Science", "Science"], skills: ["Selenium", "JIRA", "API Testing", "Agile QA"], admissionExams: ["JEE Main", "KEAM"], learningPlatforms: ["ISTQB", "Udemy", "Coursera"] },
  { id: "iot-engineering", title: "BTech Internet of Things & Smart Systems", category: "Technology", interests: ["Technology", "AI"], futureScope: "Very High", aiRisk: "Low", salary: "₹6L – ₹28L / year", startupPotential: "Excellent", globalDemand: "High", workLifeBalance: "Moderate", personalityMatch: ["technical interest", "innovation", "logical thinking"], streams: ["Science", "Computer Science"], skills: ["Arduino", "Raspberry Pi", "MQTT", "Embedded C"], admissionExams: ["JEE Main", "KEAM"], learningPlatforms: ["Coursera", "edX", "Arduino.cc"] },
  { id: "blockchain-dev", title: "Blockchain Technology & Smart Contracts", category: "Technology", interests: ["Technology", "Finance"], futureScope: "High", aiRisk: "Low", salary: "₹8L – ₹45L / year", startupPotential: "Outstanding", globalDemand: "High", workLifeBalance: "Moderate", personalityMatch: ["logical thinking", "risk tolerance", "technical interest"], streams: ["Computer Science", "Science"], skills: ["Solidity", "Ethereum", "Web3.js", "Smart Contracts"], admissionExams: ["JEE Main"], learningPlatforms: ["CryptoZombies", "Coursera", "Udemy"] },
  { id: "web-design", title: "Front-End Web Design & Creative Coding", category: "Design", interests: ["Technology", "Design"], futureScope: "High", aiRisk: "Moderate", salary: "₹4.5L – ₹20L / year", startupPotential: "Excellent", globalDemand: "High", workLifeBalance: "Good", personalityMatch: ["design", "creativity", "technical interest"], streams: ["Computer Science", "Arts", "Science"], skills: ["HTML/CSS", "JavaScript", "React", "Figma"], admissionExams: ["KEAM", "NID"], learningPlatforms: ["freeCodeCamp", "The Odin Project", "Frontend Mentor"] },
  { id: "full-stack-dev", title: "Full Stack Web Development", category: "Technology", interests: ["Technology", "Entrepreneurship"], futureScope: "Very High", aiRisk: "Low", salary: "₹6L – ₹30L / year", startupPotential: "Excellent", globalDemand: "Very High", workLifeBalance: "Good", personalityMatch: ["technical interest", "logical thinking", "innovation"], streams: ["Computer Science", "Science"], skills: ["React", "Node.js", "MongoDB", "REST APIs"], admissionExams: ["JEE Main", "KEAM"], learningPlatforms: ["The Odin Project", "Udemy", "freeCodeCamp"] },
  { id: "renewable-energy", title: "BTech Renewable Energy Engineering", category: "Technology", interests: ["Technology", "Agriculture"], futureScope: "Extremely High", aiRisk: "Very Low", salary: "₹6L – ₹30L / year", startupPotential: "Excellent", globalDemand: "Outstanding", workLifeBalance: "Good", personalityMatch: ["innovation", "technical interest", "logical thinking"], streams: ["Science"], skills: ["Solar Systems", "Wind Energy", "Power Electronics", "Grid Tech"], admissionExams: ["JEE Main", "KEAM"], learningPlatforms: ["Coursera", "edX", "NPTEL"] },
  { id: "machine-learning", title: "MTech / MSc Machine Learning", category: "AI", interests: ["AI", "Technology"], futureScope: "Extremely High", aiRisk: "Very Low", salary: "₹10L – ₹45L / year", startupPotential: "Outstanding", globalDemand: "Very High", workLifeBalance: "Moderate", personalityMatch: ["logical thinking", "analytical thinking", "technical interest"], streams: ["Science", "Computer Science"], skills: ["TensorFlow", "PyTorch", "MLOps", "Research Skills"], admissionExams: ["GATE", "JEE Advanced", "GRE"], learningPlatforms: ["Coursera", "fast.ai", "Papers with Code"] },
  { id: "nlp-specialist", title: "NLP & Conversational AI Engineer", category: "AI", interests: ["AI", "Technology"], futureScope: "Extremely High", aiRisk: "Very Low", salary: "₹9L – ₹42L / year", startupPotential: "Outstanding", globalDemand: "Very High", workLifeBalance: "Moderate", personalityMatch: ["logical thinking", "analytical thinking", "technical interest"], streams: ["Science", "Computer Science"], skills: ["BERT", "GPT", "spaCy", "Transformers"], admissionExams: ["GATE", "JEE Main"], learningPlatforms: ["Hugging Face", "Coursera", "fast.ai"] },
  { id: "ai-ethics", title: "AI Policy & Ethics Consultant", category: "AI", interests: ["AI", "Law", "Government Jobs"], futureScope: "High", aiRisk: "Very Low", salary: "₹6L – ₹25L / year", startupPotential: "Good", globalDemand: "High", workLifeBalance: "Good", personalityMatch: ["empathy", "analytical thinking", "communication"], streams: ["Humanities", "Science", "Commerce", "Arts"], skills: ["Policy Analysis", "AI Systems", "Research Writing", "Ethics"], admissionExams: ["CLAT", "UPSC", "GRE"], learningPlatforms: ["Coursera", "edX", "MIT OpenCourseWare"] },
  { id: "robot-vision", title: "BTech Computer Vision & Robot Perception", category: "AI", interests: ["AI", "Technology"], futureScope: "Very High", aiRisk: "Low", salary: "₹8L – ₹38L / year", startupPotential: "Excellent", globalDemand: "High", workLifeBalance: "Moderate", personalityMatch: ["technical interest", "logical thinking", "analytical thinking"], streams: ["Science", "Computer Science"], skills: ["OpenCV", "YOLO", "TensorFlow", "Image Processing"], admissionExams: ["JEE Main", "GATE"], learningPlatforms: ["Coursera", "PyImageSearch", "fast.ai"] },
  { id: "prompt-eng", title: "AI Prompt Engineering & Generative AI", category: "AI", interests: ["AI", "Marketing", "Media"], futureScope: "High", aiRisk: "Low", salary: "₹5L – ₹25L / year", startupPotential: "Excellent", globalDemand: "High", workLifeBalance: "Good", personalityMatch: ["creativity", "communication", "innovation"], streams: ["Computer Science", "Humanities", "Arts", "Commerce", "Science"], skills: ["Prompt Design", "LLMs", "ChatGPT API", "Content Strategy"], admissionExams: [], learningPlatforms: ["DeepLearning.AI", "Coursera", "Google"] },

  // ─── DESIGN ───────────────────────────────────────────────────────────────
  { id: "ui-ux", title: "UI/UX Product Design", category: "Design", interests: ["Design", "Technology"], futureScope: "Very High", aiRisk: "Low", salary: "₹5L – ₹24L / year", startupPotential: "Excellent", globalDemand: "Very High", workLifeBalance: "Good", personalityMatch: ["creativity", "empathy", "innovation"], streams: ["Arts", "Humanities", "Computer Science", "Science", "Commerce"], skills: ["Figma", "User Research", "Prototyping", "Design Systems"], admissionExams: ["NID", "NIFT", "CEED"], learningPlatforms: ["Google UX Design (Coursera)", "Interaction Design Foundation", "Dribbble"] },
  { id: "product-design", title: "Industrial & Product Design", category: "Design", interests: ["Design", "Technology"], futureScope: "High", aiRisk: "Low", salary: "₹6L – ₹26L / year", startupPotential: "Good", globalDemand: "High", workLifeBalance: "Good", personalityMatch: ["creativity", "innovation", "work style"], streams: ["Science", "Arts"], skills: ["SolidWorks", "3D Printing", "CAD", "Sketching"], admissionExams: ["NID", "CEED", "UCEED"], learningPlatforms: ["Coursera", "LinkedIn Learning", "IDEO U"] },
  { id: "animation", title: "BSc Animation & VFX", category: "Design", interests: ["Design", "Media"], futureScope: "High", aiRisk: "Moderate", salary: "₹4L – ₹20L / year", startupPotential: "Good", globalDemand: "High", workLifeBalance: "Moderate", personalityMatch: ["creativity", "work style", "discipline"], streams: ["Arts", "Humanities", "Computer Science"], skills: ["Maya", "After Effects", "Blender", "Compositing"], admissionExams: ["NID", "ICAT", "DSK Supinfocom"], learningPlatforms: ["LinkedIn Learning", "CG Cookie", "Rebelway"] },
  { id: "architecture", title: "Bachelor of Architecture (B.Arch)", category: "Design", interests: ["Design", "Technology"], futureScope: "Moderate", aiRisk: "Low", salary: "₹4L – ₹22L / year", startupPotential: "Good", globalDemand: "Moderate", workLifeBalance: "Moderate", personalityMatch: ["creativity", "analytical thinking", "logical thinking"], streams: ["Science", "Arts"], skills: ["AutoCAD", "Revit", "SketchUp", "3D Rendering"], admissionExams: ["NATA", "JEE Main Paper 2"], learningPlatforms: ["ArchMarathon", "NATA Guide", "Dezeen"] },
  { id: "interior-design", title: "BDes Interior Design", category: "Design", interests: ["Design", "Fashion", "Hospitality"], futureScope: "High", aiRisk: "Low", salary: "₹4L – ₹18L / year", startupPotential: "Excellent", globalDemand: "Moderate", workLifeBalance: "Good", personalityMatch: ["creativity", "communication", "empathy"], streams: ["Arts", "Humanities", "Commerce"], skills: ["AutoCAD", "SketchUp", "Color Theory", "Space Planning"], admissionExams: ["NID", "NIFT", "Pearl Academy"], learningPlatforms: ["Skillshare", "LinkedIn Learning", "IDEO U"] },
  { id: "graphic-design", title: "BSc Graphic Design", category: "Design", interests: ["Design", "Media", "Marketing"], futureScope: "High", aiRisk: "Moderate", salary: "₹3.5L – ₹18L / year", startupPotential: "Excellent", globalDemand: "High", workLifeBalance: "Good", personalityMatch: ["creativity", "work style", "innovation"], streams: ["Arts", "Humanities", "Computer Science"], skills: ["Adobe Suite", "Typography", "Branding", "Print Design"], admissionExams: ["NID", "NIFT", "Srishti"], learningPlatforms: ["Adobe Learn", "Skillshare", "Canva Design School"] },
  { id: "fashion-design", title: "BDes Fashion Design", category: "Fashion", interests: ["Fashion", "Design"], futureScope: "High", aiRisk: "Low", salary: "₹4L – ₹25L / year", startupPotential: "Outstanding", globalDemand: "High", workLifeBalance: "Moderate", personalityMatch: ["creativity", "risk tolerance", "communication"], streams: ["Arts", "Humanities", "Commerce", "Science"], skills: ["Pattern Making", "Trend Forecasting", "Draping", "Fashion Illustration"], admissionExams: ["NIFT", "NID", "Pearl Academy"], learningPlatforms: ["NIFT courses", "Skillshare", "FashionClass"] },
  { id: "textile-design", title: "BDes Textile & Apparel Design", category: "Fashion", interests: ["Fashion", "Design"], futureScope: "Good", aiRisk: "Low", salary: "₹3.5L – ₹16L / year", startupPotential: "Good", globalDemand: "Moderate", workLifeBalance: "Good", personalityMatch: ["creativity", "design", "discipline"], streams: ["Arts", "Humanities", "Commerce"], skills: ["Weaving", "Surface Design", "Dyeing", "CAD for Textiles"], admissionExams: ["NIFT", "NID", "Pearl Academy"], learningPlatforms: ["Skillshare", "Domestika", "NIFT"] },
  { id: "fashion-styling", title: "Diploma in Fashion Styling & Creative Direction", category: "Fashion", interests: ["Fashion", "Media"], futureScope: "High", aiRisk: "Low", salary: "₹4L – ₹20L / year", startupPotential: "Excellent", globalDemand: "High", workLifeBalance: "Moderate", personalityMatch: ["creativity", "design", "communication"], streams: ["Arts", "Humanities", "Commerce"], skills: ["Styling", "Color Coordination", "Photography", "Trend Research"], admissionExams: ["NIFT", "Pearl Academy"], learningPlatforms: ["Skillshare", "MasterClass", "The Fashion Stylist"] },
  { id: "fashion-marketing", title: "MBA Fashion Marketing & Luxury Brand Management", category: "Fashion", interests: ["Fashion", "Marketing", "Business"], futureScope: "High", aiRisk: "Low", salary: "₹6L – ₹30L / year", startupPotential: "Outstanding", globalDemand: "High", workLifeBalance: "Moderate", personalityMatch: ["leadership", "business", "communication"], streams: ["Commerce", "Arts", "Humanities"], skills: ["Brand Management", "Retail Strategy", "Luxury Marketing", "Analytics"], admissionExams: ["NIFT", "SNAP", "CAT"], learningPlatforms: ["Business of Fashion", "Coursera", "NIFT"] },
  { id: "game-art", title: "BDes Game Art & Asset Design", category: "Design", interests: ["Design", "Technology", "Media"], futureScope: "High", aiRisk: "Moderate", salary: "₹4L – ₹22L / year", startupPotential: "Excellent", globalDemand: "Very High", workLifeBalance: "Good", personalityMatch: ["creativity", "work style", "design"], streams: ["Arts", "Humanities", "Computer Science"], skills: ["Photoshop", "Blender", "ZBrush", "Concept Art"], admissionExams: ["NID", "ICAT", "Srishti"], learningPlatforms: ["ArtStation", "CG Cookie", "Udemy"] },

  // ─── BUSINESS & MANAGEMENT ────────────────────────────────────────────────
  { id: "bba", title: "BBA / Business Administration", category: "Business", interests: ["Business", "Entrepreneurship", "Marketing"], futureScope: "Good", aiRisk: "Moderate", salary: "₹3L – ₹15L / year", startupPotential: "Good", globalDemand: "High", workLifeBalance: "Good", personalityMatch: ["leadership", "communication", "teamwork"], streams: ["Commerce", "Humanities", "Science"], skills: ["Management", "Finance Basics", "Marketing", "Communication"], admissionExams: ["IPMAT", "SET", "CUET"], learningPlatforms: ["Coursera", "LinkedIn Learning", "edX"] },
  { id: "mba-integrated", title: "Integrated BBA + MBA", category: "Business", interests: ["Business", "Finance", "Entrepreneurship"], futureScope: "High", aiRisk: "Low", salary: "₹6L – ₹30L / year", startupPotential: "Excellent", globalDemand: "High", workLifeBalance: "Moderate", personalityMatch: ["leadership", "ambition", "communication"], streams: ["Commerce", "Humanities", "Science"], skills: ["Strategy", "Finance", "Operations", "Leadership"], admissionExams: ["IPMAT", "SET", "CAT"], learningPlatforms: ["Coursera", "Harvard Business School Online", "edX"] },
  { id: "supply-chain", title: "MBA Logistics & Supply Chain", category: "Business", interests: ["Business", "Technology"], futureScope: "Very High", aiRisk: "Moderate", salary: "₹5L – ₹25L / year", startupPotential: "Good", globalDemand: "Very High", workLifeBalance: "Moderate", personalityMatch: ["analytical thinking", "logical thinking", "teamwork"], streams: ["Commerce", "Science"], skills: ["SAP", "Procurement", "Warehouse Mgmt", "Analytics"], admissionExams: ["CAT", "MAT", "CMAT"], learningPlatforms: ["Coursera", "APICS", "LinkedIn Learning"] },
  { id: "intl-business", title: "MBA International Business", category: "Business", interests: ["Business", "Government Jobs"], futureScope: "High", aiRisk: "Moderate", salary: "₹6L – ₹30L / year", startupPotential: "Good", globalDemand: "High", workLifeBalance: "Moderate", personalityMatch: ["leadership", "communication", "analytical thinking"], streams: ["Commerce", "Science", "Humanities"], skills: ["Global Trade", "Foreign Exchange", "Cross-Cultural Mgmt", "Negotiations"], admissionExams: ["CAT", "GMAT", "XAT"], learningPlatforms: ["Coursera", "edX", "Harvard Business School Online"] },
  { id: "biz-analytics", title: "MBA Business Analytics", category: "Business", interests: ["Business", "Technology", "Finance"], futureScope: "Very High", aiRisk: "Low", salary: "₹8L – ₹32L / year", startupPotential: "Excellent", globalDemand: "Very High", workLifeBalance: "Good", personalityMatch: ["analytical thinking", "logical thinking", "technical interest"], streams: ["Commerce", "Computer Science", "Science"], skills: ["Tableau", "Power BI", "Python", "SQL"], admissionExams: ["CAT", "GMAT", "XAT"], learningPlatforms: ["Coursera", "DataCamp", "edX"] },
  { id: "hrm", title: "MBA Human Resource Management", category: "Business", interests: ["Business", "Psychology", "Education"], futureScope: "Good", aiRisk: "Low", salary: "₹4L – ₹22L / year", startupPotential: "Good", globalDemand: "High", workLifeBalance: "Outstanding", personalityMatch: ["communication", "empathy", "emotional intelligence"], streams: ["Commerce", "Humanities", "Science"], skills: ["Recruitment", "Labor Laws", "Performance Mgmt", "L&D"], admissionExams: ["CAT", "MAT", "TISS NET"], learningPlatforms: ["Coursera", "SHRM", "LinkedIn Learning"] },
  { id: "event-mgmt", title: "Diploma in Event Management", category: "Marketing", interests: ["Marketing", "Hospitality", "Media"], futureScope: "High", aiRisk: "Low", salary: "₹3.5L – ₹20L / year", startupPotential: "Excellent", globalDemand: "Moderate", workLifeBalance: "Moderate", personalityMatch: ["communication", "teamwork", "leadership"], streams: ["Commerce", "Humanities", "Arts"], skills: ["Event Planning", "Vendor Mgmt", "Budgeting", "Coordination"], admissionExams: ["NCHM JEE", "CUET"], learningPlatforms: ["Coursera", "Eventbrite Academy", "LinkedIn Learning"] },
  { id: "family-business", title: "MBA Family Business Management & Succession", category: "Entrepreneurship", interests: ["Business", "Entrepreneurship"], futureScope: "Good", aiRisk: "Low", salary: "₹5L – ₹28L / year", startupPotential: "Moderate", globalDemand: "Moderate", workLifeBalance: "Moderate", personalityMatch: ["leadership", "business", "discipline"], streams: ["Commerce", "Science"], skills: ["Governance", "Succession Planning", "Finance", "Leadership"], admissionExams: ["CAT", "GMAT"], learningPlatforms: ["Harvard Business School Online", "Coursera"] },
  { id: "retail-mgmt", title: "MBA Retail & Consumer Management", category: "Business", interests: ["Business", "Marketing"], futureScope: "High", aiRisk: "Moderate", salary: "₹4L – ₹18L / year", startupPotential: "Good", globalDemand: "Moderate", workLifeBalance: "Good", personalityMatch: ["communication", "leadership", "analytical thinking"], streams: ["Commerce", "Humanities"], skills: ["Category Management", "Store Operations", "CRM", "E-Commerce"], admissionExams: ["CAT", "MAT", "CUET"], learningPlatforms: ["Coursera", "LinkedIn Learning"] },

  // ─── FINANCE ──────────────────────────────────────────────────────────────
  { id: "finance-path", title: "BCom Finance / Financial Analyst", category: "Finance", interests: ["Finance", "Business"], futureScope: "High", aiRisk: "Moderate", salary: "₹5L – ₹28L / year", startupPotential: "Moderate", globalDemand: "High", workLifeBalance: "Moderate", personalityMatch: ["analytical thinking", "logical thinking", "discipline"], streams: ["Commerce"], skills: ["Financial Modeling", "Excel", "Accounting", "Valuation"], admissionExams: ["CUET", "IPMAT", "CA Foundation"], learningPlatforms: ["Coursera", "Wall Street Prep", "CFI"] },
  { id: "ca", title: "Chartered Accountancy (CA)", category: "Finance", interests: ["Finance", "Business"], futureScope: "High", aiRisk: "Low", salary: "₹7L – ₹40L / year", startupPotential: "Good", globalDemand: "High", workLifeBalance: "Moderate", personalityMatch: ["analytical thinking", "discipline", "logical thinking"], streams: ["Commerce"], skills: ["Auditing", "Taxation", "Financial Reporting", "GST"], admissionExams: ["CA Foundation", "CA Intermediate", "CA Final"], learningPlatforms: ["ICAI Study Material", "CA Wallah", "Unacademy"] },
  { id: "acca", title: "ACCA (Global Accounting)", category: "Finance", interests: ["Finance", "Business"], futureScope: "High", aiRisk: "Moderate", salary: "₹6L – ₹30L / year", startupPotential: "Moderate", globalDemand: "Very High", workLifeBalance: "Good", personalityMatch: ["analytical thinking", "communication", "discipline"], streams: ["Commerce"], skills: ["IFRS", "Management Accounting", "Audit", "Taxation"], admissionExams: ["ACCA Exam"], learningPlatforms: ["ACCA Learn", "OpenTuition", "Kaplan"] },
  { id: "economics", title: "BSc / BA Economics", category: "Finance", interests: ["Finance", "Government Jobs", "Business"], futureScope: "High", aiRisk: "Low", salary: "₹5L – ₹25L / year", startupPotential: "Moderate", globalDemand: "High", workLifeBalance: "Good", personalityMatch: ["analytical thinking", "logical thinking", "communication"], streams: ["Commerce", "Humanities", "Science"], skills: ["Econometrics", "Policy Analysis", "Research", "Statistics"], admissionExams: ["CUET", "Delhi University Entrance", "JNU Entrance"], learningPlatforms: ["MIT OpenCourseWare", "Khan Academy", "Coursera"] },
  { id: "invest-banking", title: "Investment Banking Path", category: "Finance", interests: ["Finance", "Business"], futureScope: "High", aiRisk: "Moderate", salary: "₹10L – ₹65L / year", startupPotential: "Moderate", globalDemand: "High", workLifeBalance: "Low", personalityMatch: ["analytical thinking", "ambition", "discipline"], streams: ["Commerce"], skills: ["DCF Modeling", "M&A", "Pitch Decks", "Bloomberg"], admissionExams: ["CAT", "GMAT", "CA Final"], learningPlatforms: ["Wall Street Prep", "Breaking Into Wall Street", "Coursera"] },
  { id: "fintech", title: "BSc Fintech & Digital Banking", category: "Finance", interests: ["Finance", "Technology", "AI"], futureScope: "Very High", aiRisk: "Low", salary: "₹7L – ₹35L / year", startupPotential: "Outstanding", globalDemand: "Very High", workLifeBalance: "Moderate", personalityMatch: ["logical thinking", "analytical thinking", "technical interest"], streams: ["Commerce", "Computer Science", "Science"], skills: ["Blockchain", "Python", "RegTech", "API Banking"], admissionExams: ["JEE Main", "CUET", "KEAM"], learningPlatforms: ["Coursera", "Udemy", "edX"] },
  { id: "cfa", title: "Chartered Financial Analyst (CFA)", category: "Finance", interests: ["Finance", "Business"], futureScope: "High", aiRisk: "Low", salary: "₹8L – ₹50L / year", startupPotential: "Moderate", globalDemand: "Very High", workLifeBalance: "Moderate", personalityMatch: ["analytical thinking", "discipline", "logical thinking"], streams: ["Commerce"], skills: ["Portfolio Management", "Equity Research", "Risk Analysis", "Ethics"], admissionExams: ["CFA Level 1", "CFA Level 2", "CFA Level 3"], learningPlatforms: ["CFA Institute", "AnalystPrep", "Kaplan"] },
  { id: "actuarial-science", title: "BSc Actuarial Science (Risk Analyst)", category: "Finance", interests: ["Finance", "Technology"], futureScope: "Very High", aiRisk: "Low", salary: "₹8L – ₹45L / year", startupPotential: "Moderate", globalDemand: "Very High", workLifeBalance: "Good", personalityMatch: ["analytical thinking", "logical thinking", "discipline"], streams: ["Commerce", "Science"], skills: ["Probability", "Statistics", "Excel", "Risk Modeling"], admissionExams: ["IAI Exam", "CT1-CT9 Exams"], learningPlatforms: ["IAI", "Coursera", "ActEd"] },
  { id: "investment-mgmt", title: "BCom Wealth & Investment Management", category: "Finance", interests: ["Finance", "Business"], futureScope: "High", aiRisk: "Moderate", salary: "₹5L – ₹24L / year", startupPotential: "Excellent", globalDemand: "High", workLifeBalance: "Good", personalityMatch: ["analytical thinking", "communication", "leadership"], streams: ["Commerce"], skills: ["Portfolio Analysis", "Mutual Funds", "Tax Planning", "Client Advisory"], admissionExams: ["CUET", "IPMAT", "CA Foundation"], learningPlatforms: ["CFI", "Investopedia Academy", "Coursera"] },

  // ─── MARKETING ────────────────────────────────────────────────────────────
  { id: "digital-marketing", title: "Digital Marketing & Growth Hacking", category: "Marketing", interests: ["Marketing", "Business", "Media"], futureScope: "Very High", aiRisk: "Moderate", salary: "₹4L – ₹22L / year", startupPotential: "Excellent", globalDemand: "Very High", workLifeBalance: "Good", personalityMatch: ["communication", "creativity", "analytical thinking"], streams: ["Commerce", "Humanities", "Arts", "Computer Science"], skills: ["SEO", "Google Ads", "Meta Ads", "Analytics"], admissionExams: ["CUET", "SET"], learningPlatforms: ["Google Digital Garage", "HubSpot Academy", "Meta Blueprint"] },
  { id: "brand-mgmt", title: "MBA Brand Management", category: "Marketing", interests: ["Marketing", "Business", "Fashion"], futureScope: "High", aiRisk: "Low", salary: "₹6L – ₹28L / year", startupPotential: "Good", globalDemand: "High", workLifeBalance: "Moderate", personalityMatch: ["leadership", "communication", "creativity"], streams: ["Commerce", "Science", "Humanities"], skills: ["Brand Strategy", "Consumer Research", "Positioning", "Campaign Mgmt"], admissionExams: ["CAT", "XAT", "SNAP"], learningPlatforms: ["Coursera", "LinkedIn Learning", "Brand New School"] },
  { id: "advertising", title: "MA Advertising & PR", category: "Marketing", interests: ["Marketing", "Media", "Design"], futureScope: "High", aiRisk: "Moderate", salary: "₹4.5L – ₹22L / year", startupPotential: "Excellent", globalDemand: "High", workLifeBalance: "Moderate", personalityMatch: ["communication", "creativity", "risk tolerance"], streams: ["Commerce", "Humanities", "Arts"], skills: ["Copywriting", "Campaign Strategy", "Media Planning", "PR Writing"], admissionExams: ["CUET", "IIMC", "XIC"], learningPlatforms: ["Coursera", "CopyHackers", "HubSpot"] },
  { id: "pr-corporate", title: "BA Public Relations & Corporate Communication", category: "Marketing", interests: ["Marketing", "Media", "Law"], futureScope: "High", aiRisk: "Low", salary: "₹4L – ₹18L / year", startupPotential: "Excellent", globalDemand: "High", workLifeBalance: "Good", personalityMatch: ["communication", "social confidence", "emotional intelligence"], streams: ["Arts", "Humanities", "Commerce"], skills: ["Media Relations", "Crisis Communication", "Press Releases", "Stakeholder Mgmt"], admissionExams: ["CUET", "XIC", "IIMC"], learningPlatforms: ["Coursera", "PR Daily", "LinkedIn Learning"] },
  { id: "seo-content", title: "SEO & Content Strategy Specialist", category: "Marketing", interests: ["Marketing", "Media", "Technology"], futureScope: "High", aiRisk: "Moderate", salary: "₹3.5L – ₹16L / year", startupPotential: "Excellent", globalDemand: "High", workLifeBalance: "Good", personalityMatch: ["communication", "creativity", "analytical thinking"], streams: ["Commerce", "Humanities", "Computer Science"], skills: ["Content Writing", "SEO Tools", "Keyword Research", "Analytics"], admissionExams: [], learningPlatforms: ["HubSpot Academy", "Moz", "Ahrefs Academy"] },
  { id: "ecommerce", title: "BBA E-Commerce & Retail", category: "Marketing", interests: ["Marketing", "Business", "Technology"], futureScope: "Very High", aiRisk: "Moderate", salary: "₹4L – ₹22L / year", startupPotential: "Excellent", globalDemand: "Very High", workLifeBalance: "Good", personalityMatch: ["entrepreneurship", "creativity", "communication"], streams: ["Commerce"], skills: ["Shopify", "Marketplace Selling", "Growth Marketing", "Analytics"], admissionExams: ["CUET", "IPMAT"], learningPlatforms: ["Shopify Learn", "Udemy", "Google"] },
  { id: "product-mgmt", title: "MBA Product Management", category: "Business", interests: ["Business", "Technology", "Design"], futureScope: "Very High", aiRisk: "Low", salary: "₹10L – ₹45L / year", startupPotential: "Outstanding", globalDemand: "Very High", workLifeBalance: "Moderate", personalityMatch: ["leadership", "analytical thinking", "innovation"], streams: ["Commerce", "Science", "Computer Science"], skills: ["Roadmapping", "Agile", "User Stories", "Data Analysis"], admissionExams: ["CAT", "GMAT", "XAT"], learningPlatforms: ["Product School", "Reforge", "Coursera"] },

  // ─── ENTREPRENEURSHIP ─────────────────────────────────────────────────────
  { id: "entrepreneurship", title: "Entrepreneurship & Venture Launch", category: "Entrepreneurship", interests: ["Entrepreneurship", "Business"], futureScope: "Very High", aiRisk: "Very Low", salary: "₹0 – Unlimited", startupPotential: "Outstanding", globalDemand: "Very High", workLifeBalance: "Low", personalityMatch: ["leadership", "risk tolerance", "entrepreneurship"], streams: ["Commerce", "Science", "Computer Science", "Humanities", "Arts"], skills: ["Startup Thinking", "Fundraising", "Team Building", "Business Model"], admissionExams: ["IPMAT", "CAT", "CUET"], learningPlatforms: ["Y Combinator", "Founder Institute", "Coursera"] },
  { id: "social-entrepreneurship", title: "Social Entrepreneurship & Non-Profit Leadership", category: "Entrepreneurship", interests: ["Entrepreneurship", "Education", "Psychology"], futureScope: "High", aiRisk: "Very Low", salary: "₹3L – ₹15L / year", startupPotential: "Outstanding", globalDemand: "Moderate", workLifeBalance: "Good", personalityMatch: ["leadership", "empathy", "risk tolerance"], streams: ["Arts", "Humanities", "Commerce", "Science"], skills: ["Impact Measurement", "Grant Writing", "NGO Management", "Community Outreach"], admissionExams: ["TISS NET", "CUET"], learningPlatforms: ["Acumen Academy", "Coursera", "edX"] },

  // ─── AGRICULTURE ──────────────────────────────────────────────────────────
  { id: "agriculture", title: "BSc Agriculture", category: "Agriculture", interests: ["Agriculture"], futureScope: "Very High", aiRisk: "Low", salary: "₹3L – ₹18L / year", startupPotential: "Excellent", globalDemand: "Very High", workLifeBalance: "Good", personalityMatch: ["logical thinking", "discipline", "technical interest"], streams: ["Science"], skills: ["Crop Science", "Soil Science", "Pest Management", "Farm Planning"], admissionExams: ["ICAR AIEEA", "KEAM", "CUET"], learningPlatforms: ["NPTEL", "Coursera", "ICAR e-Courses"] },
  { id: "agritech-farming", title: "BTech Agritech & Precision Farming", category: "Agriculture", interests: ["Agriculture", "Technology"], futureScope: "Very High", aiRisk: "Low", salary: "₹4.5L – ₹20L / year", startupPotential: "Outstanding", globalDemand: "High", workLifeBalance: "Moderate", personalityMatch: ["technical interest", "logical thinking", "discipline"], streams: ["Science"], skills: ["Drone Tech", "Precision Agriculture", "IoT Sensors", "GIS"], admissionExams: ["JEE Main", "KEAM", "ICAR AIEEA"], learningPlatforms: ["Coursera", "NPTEL", "FutureLearn"] },
  { id: "horticulture", title: "BSc Horticulture & Landscaping", category: "Agriculture", interests: ["Agriculture", "Design"], futureScope: "Good", aiRisk: "Low", salary: "₹3L – ₹14L / year", startupPotential: "Excellent", globalDemand: "Moderate", workLifeBalance: "Good", personalityMatch: ["design", "creativity", "discipline"], streams: ["Science"], skills: ["Plant Science", "Landscape Design", "Nursery Management", "Floriculture"], admissionExams: ["ICAR AIEEA", "KEAM"], learningPlatforms: ["ICAR e-Courses", "Coursera"] },
  { id: "food-tech", title: "BTech Food Technology", category: "Agriculture", interests: ["Agriculture", "Healthcare"], futureScope: "High", aiRisk: "Low", salary: "₹3.5L – ₹18L / year", startupPotential: "Excellent", globalDemand: "High", workLifeBalance: "Good", personalityMatch: ["logical thinking", "discipline", "technical interest"], streams: ["Science"], skills: ["Food Safety", "HACCP", "R&D", "Quality Control"], admissionExams: ["JEE Main", "KEAM", "ICAR AIEEA"], learningPlatforms: ["Coursera", "NPTEL", "edX"] },
  { id: "env-science", title: "BSc Environmental Science", category: "Agriculture", interests: ["Agriculture", "Government Jobs"], futureScope: "Very High", aiRisk: "Low", salary: "₹3L – ₹15L / year", startupPotential: "Good", globalDemand: "Very High", workLifeBalance: "Good", personalityMatch: ["logical thinking", "discipline", "empathy"], streams: ["Science"], skills: ["Ecology", "Environmental Law", "GIS", "Research"], admissionExams: ["CUET", "JNU Entrance", "BHU Entrance"], learningPlatforms: ["Coursera", "edX", "NPTEL"] },
  { id: "vet-science", title: "Bachelor of Veterinary Science (BVSc)", category: "Agriculture", interests: ["Agriculture", "Healthcare"], futureScope: "High", aiRisk: "Very Low", salary: "₹4L – ₹16L / year", startupPotential: "Excellent", globalDemand: "High", workLifeBalance: "Good", personalityMatch: ["empathy", "discipline", "logical thinking"], streams: ["Science"], skills: ["Animal Medicine", "Surgery", "Public Health", "Animal Nutrition"], admissionExams: ["NEET", "KEAM", "VCRC"], learningPlatforms: ["ICAR e-Courses", "Coursera", "Merck Vet Manual"] },

  // ─── SPORTS ───────────────────────────────────────────────────────────────
  { id: "sports-mgmt", title: "Bachelor of Sports Management", category: "Sports", interests: ["Sports", "Business"], futureScope: "High", aiRisk: "Low", salary: "₹4L – ₹20L / year", startupPotential: "Good", globalDemand: "High", workLifeBalance: "Good", personalityMatch: ["leadership", "teamwork", "communication"], streams: ["Commerce", "Humanities", "Science"], skills: ["Sports Marketing", "Event Management", "Sponsorship", "Team Management"], admissionExams: ["CUET", "AISSEE"], learningPlatforms: ["Coursera", "Udemy", "LinkedIn Learning"] },
  { id: "sports-science", title: "BSc Sports Science & Coaching", category: "Sports", interests: ["Sports", "Healthcare"], futureScope: "High", aiRisk: "Low", salary: "₹4L – ₹18L / year", startupPotential: "Good", globalDemand: "Moderate", workLifeBalance: "Good", personalityMatch: ["logical thinking", "discipline", "analytical thinking"], streams: ["Science"], skills: ["Physiology", "Biomechanics", "Nutrition", "Coaching Methods"], admissionExams: ["CUET", "LNIPE Entrance"], learningPlatforms: ["Coursera", "NSCA", "UK Coaching"] },
  { id: "sports-coaching", title: "Diploma in Sports Coaching & Training", category: "Sports", interests: ["Sports"], futureScope: "Good", aiRisk: "Very Low", salary: "₹3L – ₹15L / year", startupPotential: "Excellent", globalDemand: "Moderate", workLifeBalance: "Moderate", personalityMatch: ["leadership", "discipline", "teamwork"], streams: ["Arts", "Humanities", "Science", "Commerce"], skills: ["Strength Training", "Tactical Analysis", "Youth Coaching", "Sports Psychology"], admissionExams: ["CUET", "SAI Entrance"], learningPlatforms: ["Sports Coaching Scotland", "UK Coaching", "Coursera"] },
  { id: "sports-journalism", title: "BA Sports Journalism & Broadcasting", category: "Sports", interests: ["Sports", "Media"], futureScope: "High", aiRisk: "Moderate", salary: "₹4L – ₹20L / year", startupPotential: "Good", globalDemand: "High", workLifeBalance: "Moderate", personalityMatch: ["communication", "social confidence", "discipline"], streams: ["Humanities", "Arts", "Commerce"], skills: ["Sports Writing", "Broadcasting", "Video Production", "Social Media"], admissionExams: ["IIMC", "XIC", "CUET"], learningPlatforms: ["Coursera", "ESPN Academy", "Knight Center"] },
  { id: "fitness-nutrition", title: "BSc Fitness & Nutrition Management", category: "Sports", interests: ["Sports", "Healthcare"], futureScope: "High", aiRisk: "Very Low", salary: "₹3.5L – ₹15L / year", startupPotential: "Excellent", globalDemand: "High", workLifeBalance: "Good", personalityMatch: ["empathy", "discipline", "communication"], streams: ["Science", "Humanities"], skills: ["Nutrition Science", "Exercise Physiology", "Wellness Coaching", "Diet Planning"], admissionExams: ["CUET", "LNIPE Entrance"], learningPlatforms: ["NASM", "ACE Fitness", "Coursera"] },

  // ─── HEALTHCARE ───────────────────────────────────────────────────────────
  { id: "nursing", title: "BSc Nursing", category: "Healthcare", interests: ["Healthcare"], futureScope: "Very High", aiRisk: "Very Low", salary: "₹3L – ₹20L / year", startupPotential: "Moderate", globalDemand: "Outstanding", workLifeBalance: "Moderate", personalityMatch: ["empathy", "discipline", "teamwork"], streams: ["Science"], skills: ["Patient Care", "Clinical Procedures", "Pharmacology", "Emergency Response"], admissionExams: ["NEET", "KEAM", "State Nursing Entrance"], learningPlatforms: ["NursingWorld", "Coursera", "Khan Academy Health"] },
  { id: "pharmacy", title: "Bachelor of Pharmacy (B.Pharm)", category: "Healthcare", interests: ["Healthcare", "Agriculture"], futureScope: "High", aiRisk: "Low", salary: "₹3L – ₹18L / year", startupPotential: "Good", globalDemand: "High", workLifeBalance: "Good", personalityMatch: ["discipline", "analytical thinking", "logical thinking"], streams: ["Science"], skills: ["Pharmaceutical Chemistry", "Clinical Pharmacy", "Drug Regulatory Affairs", "R&D"], admissionExams: ["NEET", "KEAM", "GPAT"], learningPlatforms: ["Coursera", "PharmD Resources", "Medscape"] },
  { id: "physiotherapy", title: "Bachelor of Physiotherapy (BPT)", category: "Healthcare", interests: ["Healthcare", "Sports"], futureScope: "High", aiRisk: "Very Low", salary: "₹3L – ₹15L / year", startupPotential: "Excellent", globalDemand: "High", workLifeBalance: "Good", personalityMatch: ["empathy", "communication", "work style"], streams: ["Science"], skills: ["Manual Therapy", "Exercise Prescription", "Anatomy", "Patient Assessment"], admissionExams: ["NEET", "KEAM", "State Physiotherapy Entrance"], learningPlatforms: ["Physiopedia", "Coursera", "YouTube Medical"] },
  { id: "biomedical-eng", title: "BTech Biomedical Engineering", category: "Healthcare", interests: ["Healthcare", "Technology"], futureScope: "Very High", aiRisk: "Low", salary: "₹5L – ₹26L / year", startupPotential: "Excellent", globalDemand: "Very High", workLifeBalance: "Good", personalityMatch: ["technical interest", "logical thinking", "empathy"], streams: ["Science"], skills: ["Medical Devices", "Signal Processing", "Biomechanics", "Regulatory Affairs"], admissionExams: ["JEE Main", "KEAM", "NEET (for some programs)"], learningPlatforms: ["Coursera", "NPTEL", "edX"] },
  { id: "hospital-admin", title: "Bachelor of Hospital Administration (BHA)", category: "Healthcare", interests: ["Healthcare", "Business"], futureScope: "Very High", aiRisk: "Low", salary: "₹4.5L – ₹22L / year", startupPotential: "Good", globalDemand: "High", workLifeBalance: "Moderate", personalityMatch: ["leadership", "discipline", "empathy"], streams: ["Commerce", "Science", "Humanities"], skills: ["Healthcare Finance", "Hospital Operations", "Quality Mgmt", "Health Policy"], admissionExams: ["CUET", "TISS NET", "NCHM JEE"], learningPlatforms: ["Coursera", "edX", "AIIMS Health Admin"] },
  { id: "nutrition-diet", title: "BSc Nutrition & Dietetics", category: "Healthcare", interests: ["Healthcare", "Agriculture"], futureScope: "High", aiRisk: "Very Low", salary: "₹3L – ₹15L / year", startupPotential: "Excellent", globalDemand: "High", workLifeBalance: "Good", personalityMatch: ["empathy", "communication", "science"], streams: ["Science"], skills: ["Clinical Nutrition", "Diet Planning", "Food Science", "Counseling"], admissionExams: ["NEET", "CUET", "State Entrance"], learningPlatforms: ["Coursera", "Stanford Health", "AND Career Center"] },
  { id: "biotech", title: "BTech Biotechnology", category: "Healthcare", interests: ["Healthcare", "Agriculture", "Technology"], futureScope: "Very High", aiRisk: "Low", salary: "₹4L – ₹25L / year", startupPotential: "Excellent", globalDemand: "Very High", workLifeBalance: "Good", personalityMatch: ["analytical thinking", "logical thinking", "technical interest"], streams: ["Science"], skills: ["Genetic Engineering", "Cell Biology", "Bioinformatics", "Lab Techniques"], admissionExams: ["JEE Main", "KEAM", "ICAR AIEEA"], learningPlatforms: ["Coursera", "edX", "NPTEL"] },
  { id: "marine-eng", title: "BTech Marine Engineering", category: "Aviation", interests: ["Aviation", "Technology"], futureScope: "Good", aiRisk: "Low", salary: "₹6L – ₹24L / year", startupPotential: "Low", globalDemand: "High", workLifeBalance: "Moderate", personalityMatch: ["discipline", "technical interest", "risk tolerance"], streams: ["Science"], skills: ["Marine Diesel Engines", "Ship Systems", "Navigation", "STCW Training"], admissionExams: ["IMU CET", "JEE Main"], learningPlatforms: ["IMU Courses", "Coursera", "NPTEL"] },

  // ─── PSYCHOLOGY ───────────────────────────────────────────────────────────
  { id: "psychology", title: "BSc / BA Psychology", category: "Psychology", interests: ["Psychology", "Education", "Healthcare"], futureScope: "High", aiRisk: "Very Low", salary: "₹3L – ₹15L / year", startupPotential: "Good", globalDemand: "High", workLifeBalance: "Good", personalityMatch: ["empathy", "communication", "emotional intelligence"], streams: ["Humanities", "Science"], skills: ["Counseling", "Research Methods", "Behavioral Analysis", "Psychological Testing"], admissionExams: ["CUET", "Delhi University Entrance", "BHU Entrance"], learningPlatforms: ["Coursera", "Khan Academy", "APA Resources"] },
  { id: "clinical-psychology", title: "MSc Clinical Psychology", category: "Psychology", interests: ["Psychology", "Healthcare"], futureScope: "Very High", aiRisk: "Very Low", salary: "₹4L – ₹20L / year", startupPotential: "Excellent", globalDemand: "High", workLifeBalance: "Good", personalityMatch: ["empathy", "discipline", "emotional intelligence"], streams: ["Science", "Humanities"], skills: ["Psychotherapy", "Diagnosis", "CBT", "Assessment Tools"], admissionExams: ["CUET", "NIMHANS", "TISS NET"], learningPlatforms: ["Coursera", "APA", "Beck Institute"] },
  { id: "counseling-psych", title: "MSc Counseling Psychology & Therapy", category: "Psychology", interests: ["Psychology", "Education", "Healthcare"], futureScope: "Very High", aiRisk: "Very Low", salary: "₹4L – ₹18L / year", startupPotential: "Excellent", globalDemand: "High", workLifeBalance: "Good", personalityMatch: ["empathy", "emotional intelligence", "communication"], streams: ["Humanities", "Science"], skills: ["Active Listening", "Solution-Focused Therapy", "Mindfulness", "CBT"], admissionExams: ["CUET", "NIMHANS", "State Entrance"], learningPlatforms: ["Coursera", "APA", "Therapy Aid"] },
  { id: "org-behavior", title: "Organizational Behavior & Corporate Psychology", category: "Psychology", interests: ["Psychology", "Business", "Entrepreneurship"], futureScope: "High", aiRisk: "Low", salary: "₹5L – ₹24L / year", startupPotential: "Good", globalDemand: "High", workLifeBalance: "Good", personalityMatch: ["analytical thinking", "communication", "emotional intelligence"], streams: ["Humanities", "Commerce", "Science"], skills: ["OD Consulting", "Group Dynamics", "Leadership Coaching", "Culture Design"], admissionExams: ["CAT", "TISS NET", "XAT"], learningPlatforms: ["Coursera", "Wharton Online", "edX"] },

  // ─── MEDIA ────────────────────────────────────────────────────────────────
  { id: "journalism", title: "BA Journalism & Mass Communication", category: "Media", interests: ["Media", "Law"], futureScope: "Moderate", aiRisk: "Moderate", salary: "₹3L – ₹18L / year", startupPotential: "Good", globalDemand: "Moderate", workLifeBalance: "Moderate", personalityMatch: ["communication", "risk tolerance", "empathy"], streams: ["Humanities", "Arts"], skills: ["Investigative Reporting", "Video Journalism", "Writing", "Digital Media"], admissionExams: ["IIMC Entrance", "XIC Entrance", "CUET"], learningPlatforms: ["IIMC Resources", "Knight Center", "Reuters Journalism"] },
  { id: "filmmaking", title: "Bachelor of Film Making & Direction", category: "Media", interests: ["Media", "Design", "Entrepreneurship"], futureScope: "High", aiRisk: "Very Low", salary: "₹4L – ₹80L / year", startupPotential: "Excellent", globalDemand: "High", workLifeBalance: "Moderate", personalityMatch: ["creativity", "leadership", "communication"], streams: ["Arts", "Humanities"], skills: ["Screenplay Writing", "Direction", "Editing", "Cinematography"], admissionExams: ["FTII", "Whistling Woods", "Srishti"], learningPlatforms: ["MasterClass", "Film Riot", "Coursera"] },
  { id: "media-prod", title: "BSc Media Production & Broadcasting", category: "Media", interests: ["Media", "Technology"], futureScope: "Good", aiRisk: "Moderate", salary: "₹3L – ₹18L / year", startupPotential: "Good", globalDemand: "Moderate", workLifeBalance: "Good", personalityMatch: ["creativity", "communication", "work style"], streams: ["Arts", "Humanities"], skills: ["Video Production", "Audio Mixing", "Live Broadcasting", "OTT Content"], admissionExams: ["IIMC", "XIC", "CUET"], learningPlatforms: ["Coursera", "LinkedIn Learning", "Udemy"] },
  { id: "digital-media", title: "BA Digital Media & Content Creation", category: "Media", interests: ["Media", "Marketing", "Technology"], futureScope: "Very High", aiRisk: "Moderate", salary: "₹3.5L – ₹18L / year", startupPotential: "Excellent", globalDemand: "Very High", workLifeBalance: "Good", personalityMatch: ["creativity", "communication", "social confidence"], streams: ["Arts", "Humanities", "Commerce"], skills: ["Content Strategy", "YouTube", "Reels/TikTok", "Podcasting"], admissionExams: ["CUET", "XIC"], learningPlatforms: ["Creator Academy", "HubSpot", "Coursera"] },
  { id: "audio-engineering", title: "BSc Audio Engineering & Sound Design", category: "Media", interests: ["Media", "Technology", "Design"], futureScope: "High", aiRisk: "Low", salary: "₹4L – ₹25L / year", startupPotential: "Excellent", globalDemand: "High", workLifeBalance: "Moderate", personalityMatch: ["technical interest", "creativity", "discipline"], streams: ["Arts", "Science", "Computer Science"], skills: ["Pro Tools", "Logic Pro", "Live Sound", "Acoustic Treatment"], admissionExams: ["KM Music", "SAE Institute", "Whistling Woods"], learningPlatforms: ["Coursera", "Soundfly", "Berklee Online"] },
  { id: "vis-comm", title: "BSc Visual Communication", category: "Media", interests: ["Media", "Design"], futureScope: "High", aiRisk: "Low", salary: "₹4L – ₹20L / year", startupPotential: "Excellent", globalDemand: "High", workLifeBalance: "Good", personalityMatch: ["creativity", "communication", "innovation"], streams: ["Arts", "Humanities", "Media"], skills: ["Photography", "Graphic Design", "Motion Graphics", "Branding"], admissionExams: ["NID", "NIFT", "KCET"], learningPlatforms: ["Skillshare", "Adobe Learn", "Coursera"] },

  // ─── LAW ──────────────────────────────────────────────────────────────────
  { id: "law", title: "Integrated BA LLB / BBA LLB", category: "Law", interests: ["Law", "Government Jobs"], futureScope: "High", aiRisk: "Low", salary: "₹5L – ₹45L / year", startupPotential: "Good", globalDemand: "High", workLifeBalance: "Moderate", personalityMatch: ["logical thinking", "communication", "analytical thinking"], streams: ["Humanities", "Commerce", "Science"], skills: ["Legal Research", "Drafting", "Advocacy", "Contract Law"], admissionExams: ["CLAT", "AILET", "LSAT India"], learningPlatforms: ["Bar & Bench", "SCC Online", "Coursera"] },
  { id: "criminology", title: "BSc Criminology & Forensic Science", category: "Law", interests: ["Law", "Government Jobs"], futureScope: "Moderate", aiRisk: "Very Low", salary: "₹4L – ₹18L / year", startupPotential: "Low", globalDemand: "Moderate", workLifeBalance: "Moderate", personalityMatch: ["analytical thinking", "discipline", "logical thinking"], streams: ["Science"], skills: ["Forensic Analysis", "Criminal Law", "Investigation Techniques", "Lab Skills"], admissionExams: ["CLAT", "CUET", "State Forensic Entrance"], learningPlatforms: ["Coursera", "edX", "Forensics Science International"] },
  { id: "cyber-law", title: "Post Graduate Diploma in Cyber Law & Security", category: "Law", interests: ["Law", "Technology"], futureScope: "Very High", aiRisk: "Low", salary: "₹6L – ₹30L / year", startupPotential: "Excellent", globalDemand: "High", workLifeBalance: "Good", personalityMatch: ["logical thinking", "analytical thinking", "technical interest"], streams: ["Science", "Computer Science", "Commerce", "Humanities"], skills: ["IT Act", "Cyber Crime Law", "Data Privacy", "Digital Evidence"], admissionExams: ["CLAT", "University Entrance"], learningPlatforms: ["Coursera", "NLU Resources", "CyberLaw.in"] },
  { id: "intl-law", title: "LLM International Law & Treaty Studies", category: "Law", interests: ["Law", "Government Jobs"], futureScope: "High", aiRisk: "Very Low", salary: "₹7L – ₹38L / year", startupPotential: "Good", globalDemand: "Very High", workLifeBalance: "Moderate", personalityMatch: ["analytical thinking", "communication", "logical thinking"], streams: ["Humanities", "Commerce", "Science"], skills: ["International Relations", "Treaty Law", "UN Law", "Dispute Resolution"], admissionExams: ["CLAT PG", "University LLM Entrance", "GRE"], learningPlatforms: ["Coursera", "ICJ Resources", "Bar & Bench"] },
  { id: "corporate-law", title: "Corporate Law & Compliance", category: "Law", interests: ["Law", "Business", "Finance"], futureScope: "High", aiRisk: "Low", salary: "₹8L – ₹50L / year", startupPotential: "Good", globalDemand: "High", workLifeBalance: "Moderate", personalityMatch: ["analytical thinking", "discipline", "communication"], streams: ["Commerce", "Humanities", "Science"], skills: ["Company Law", "SEBI Regulations", "M&A Due Diligence", "Compliance"], admissionExams: ["CLAT", "AILET", "LSAT India"], learningPlatforms: ["Bar & Bench", "Coursera", "SCC Online"] },

  // ─── GOVERNMENT JOBS ──────────────────────────────────────────────────────
  { id: "gov-admin", title: "Civil Services (IAS/IPS/IFS) Preparation", category: "Government Jobs", interests: ["Government Jobs", "Law"], futureScope: "Stable", aiRisk: "Very Low", salary: "₹6L – ₹24L / year", startupPotential: "Low", globalDemand: "High", workLifeBalance: "Moderate", personalityMatch: ["leadership", "discipline", "analytical thinking"], streams: ["Humanities", "Science", "Commerce"], skills: ["General Studies", "Essay Writing", "Current Affairs", "Governance"], admissionExams: ["UPSC CSE", "State PSC"], learningPlatforms: ["Vajiram & Ravi", "Unacademy", "BYJU's UPSC"] },
  { id: "public-admin", title: "MA Public Administration", category: "Government Jobs", interests: ["Government Jobs", "Business"], futureScope: "Stable", aiRisk: "Very Low", salary: "₹5L – ₹18L / year", startupPotential: "Low", globalDemand: "Moderate", workLifeBalance: "Good", personalityMatch: ["leadership", "discipline", "analytical thinking"], streams: ["Humanities", "Commerce"], skills: ["Public Policy", "Administrative Law", "Governance", "Budgeting"], admissionExams: ["CUET", "JNU Entrance", "TISS NET"], learningPlatforms: ["Coursera", "IGNOU", "Unacademy"] },
  { id: "pol-science", title: "BA Political Science", category: "Government Jobs", interests: ["Government Jobs", "Law", "Education"], futureScope: "Stable", aiRisk: "Low", salary: "₹3L – ₹15L / year", startupPotential: "Low", globalDemand: "Moderate", workLifeBalance: "Good", personalityMatch: ["analytical thinking", "communication", "logical thinking"], streams: ["Humanities"], skills: ["Political Theory", "International Relations", "Research", "Policy Analysis"], admissionExams: ["CUET", "Delhi University Entrance"], learningPlatforms: ["Coursera", "Khan Academy", "IGNOU"] },
  { id: "defence-studies", title: "BA Defence & Strategic Studies (NDA Path)", category: "Government Jobs", interests: ["Government Jobs", "Sports"], futureScope: "Stable", aiRisk: "Very Low", salary: "₹5L – ₹20L / year", startupPotential: "Low", globalDemand: "Moderate", workLifeBalance: "Moderate", personalityMatch: ["discipline", "leadership", "risk tolerance"], streams: ["Humanities", "Science", "Commerce"], skills: ["Leadership", "Physical Fitness", "Strategy", "Defence Law"], admissionExams: ["NDA", "CDS", "AFCAT"], learningPlatforms: ["Unacademy", "Testbook", "Coursera"] },
  { id: "disaster-mgmt", title: "PG Diploma in Disaster Management", category: "Government Jobs", interests: ["Government Jobs", "Healthcare"], futureScope: "High", aiRisk: "Very Low", salary: "₹4L – ₹16L / year", startupPotential: "Low", globalDemand: "Moderate", workLifeBalance: "Low", personalityMatch: ["discipline", "leadership", "risk tolerance"], streams: ["Science", "Commerce", "Humanities"], skills: ["Emergency Response", "Crisis Management", "GIS", "Relief Operations"], admissionExams: ["CUET", "IGNOU Entrance", "NIDM"], learningPlatforms: ["NIDM", "Coursera", "FEMA Training"] },

  // ─── EDUCATION ────────────────────────────────────────────────────────────
  { id: "teaching", title: "Bachelor of Education (B.Ed)", category: "Education", interests: ["Education", "Psychology"], futureScope: "Stable", aiRisk: "Low", salary: "₹3L – ₹15L / year", startupPotential: "Low", globalDemand: "High", workLifeBalance: "Outstanding", personalityMatch: ["communication", "empathy", "discipline"], streams: ["Science", "Commerce", "Humanities"], skills: ["Pedagogy", "Classroom Management", "Curriculum Design", "Subject Expertise"], admissionExams: ["DUET", "BHU Entrance", "State B.Ed Entrance"], learningPlatforms: ["DIKSHA", "SWAYAM", "Coursera"] },
  { id: "early-edu", title: "Early Childhood Education Diploma", category: "Education", interests: ["Education", "Psychology"], futureScope: "Good", aiRisk: "Very Low", salary: "₹2.5L – ₹10L / year", startupPotential: "Good", globalDemand: "Moderate", workLifeBalance: "Outstanding", personalityMatch: ["empathy", "communication", "emotional intelligence"], streams: ["Humanities", "Arts"], skills: ["Child Development", "Play-Based Learning", "ECE Methods", "Special Needs"], admissionExams: ["CUET", "State ECE Entrance"], learningPlatforms: ["Coursera", "NIPCCD", "Khan Academy"] },
  { id: "special-edu", title: "Bachelor of Special Education (B.Ed Spl Ed)", category: "Education", interests: ["Education", "Healthcare", "Psychology"], futureScope: "High", aiRisk: "Very Low", salary: "₹3L – ₹14L / year", startupPotential: "Good", globalDemand: "High", workLifeBalance: "Outstanding", personalityMatch: ["empathy", "communication", "discipline"], streams: ["Humanities", "Science", "Commerce", "Arts"], skills: ["Learning Disabilities", "Autism Support", "IEP Development", "Sensory Integration"], admissionExams: ["State B.Ed Entrance", "NISHTHA"], learningPlatforms: ["NISH", "DIKSHA", "Coursera"] },
  { id: "e-learning-design", title: "Master of Instructional Design & E-Learning", category: "Education", interests: ["Education", "Technology", "Design"], futureScope: "Very High", aiRisk: "Low", salary: "₹5L – ₹20L / year", startupPotential: "Excellent", globalDemand: "High", workLifeBalance: "Good", personalityMatch: ["design", "creativity", "technology"], streams: ["Computer Science", "Humanities", "Science", "Commerce"], skills: ["LMS Design", "Video Scripting", "Articulate 360", "Adult Learning Theory"], admissionExams: ["CUET", "University Entrance"], learningPlatforms: ["Coursera", "eLearning Industry", "LinkedIn Learning"] },

  // ─── HOSPITALITY ──────────────────────────────────────────────────────────
  { id: "hotel-mgmt", title: "Bachelor of Hotel Management (BHM)", category: "Hospitality", interests: ["Hospitality", "Business"], futureScope: "Good", aiRisk: "Low", salary: "₹3L – ₹18L / year", startupPotential: "Good", globalDemand: "High", workLifeBalance: "Moderate", personalityMatch: ["communication", "teamwork", "empathy"], streams: ["Humanities", "Commerce", "Arts"], skills: ["Food & Beverage", "Front Office", "Housekeeping", "Revenue Mgmt"], admissionExams: ["NCHM JEE", "NCHMCT", "State Hotel Mgmt Entrance"], learningPlatforms: ["IHM Resources", "Coursera", "FutureLearn"] },
  { id: "culinary-arts", title: "BA Culinary Arts (Chef Training)", category: "Hospitality", interests: ["Hospitality"], futureScope: "High", aiRisk: "Very Low", salary: "₹3L – ₹22L / year", startupPotential: "Excellent", globalDemand: "High", workLifeBalance: "Moderate", personalityMatch: ["creativity", "discipline", "work style"], streams: ["Arts", "Humanities"], skills: ["Cooking Techniques", "Pastry", "Food Plating", "Kitchen Management"], admissionExams: ["NCHM JEE", "Culinary Institute Entrance"], learningPlatforms: ["MasterClass", "Rouxbe Online", "Coursera"] },
  { id: "hospitality-mgmt", title: "MBA Hospitality Management", category: "Hospitality", interests: ["Hospitality", "Business"], futureScope: "Good", aiRisk: "Low", salary: "₹4L – ₹20L / year", startupPotential: "Good", globalDemand: "High", workLifeBalance: "Moderate", personalityMatch: ["communication", "leadership", "teamwork"], streams: ["Commerce", "Humanities"], skills: ["Revenue Management", "Guest Experience", "Hotel Finance", "F&B Operations"], admissionExams: ["CAT", "MAT", "NCHM JEE"], learningPlatforms: ["Coursera", "IHM Resources", "LinkedIn Learning"] },
  { id: "travel-tourism", title: "BA Travel & Tourism Management", category: "Hospitality", interests: ["Hospitality", "Business"], futureScope: "Good", aiRisk: "Moderate", salary: "₹3L – ₹14L / year", startupPotential: "Excellent", globalDemand: "High", workLifeBalance: "Good", personalityMatch: ["communication", "empathy", "work style"], streams: ["Humanities", "Commerce", "Arts"], skills: ["Tour Planning", "Destination Knowledge", "GDS Systems", "Customer Service"], admissionExams: ["CUET", "NCHM JEE", "State Tourism Entrance"], learningPlatforms: ["Tourism Training", "Coursera", "Amadeus Training"] },
  { id: "spa-wellness", title: "PG Diploma in Spa & Wellness Resort Management", category: "Hospitality", interests: ["Hospitality", "Healthcare"], futureScope: "Good", aiRisk: "Low", salary: "₹4L – ₹18L / year", startupPotential: "Excellent", globalDemand: "Moderate", workLifeBalance: "Moderate", personalityMatch: ["empathy", "communication", "business"], streams: ["Humanities", "Commerce", "Arts"], skills: ["Spa Management", "Wellness Programs", "Ayurveda Basics", "Guest Services"], admissionExams: ["State Entrance", "NCHM JEE"], learningPlatforms: ["CIBTAC", "Coursera", "CIDESCO"] },

  // ─── AVIATION ─────────────────────────────────────────────────────────────
  { id: "aviation", title: "BBA Aviation Management", category: "Aviation", interests: ["Aviation", "Business"], futureScope: "Good", aiRisk: "Low", salary: "₹4L – ₹16L / year", startupPotential: "Moderate", globalDemand: "High", workLifeBalance: "Good", personalityMatch: ["leadership", "discipline", "teamwork"], streams: ["Science", "Commerce", "Humanities"], skills: ["Airport Operations", "Aviation Safety", "Airline Management", "ICAO Regulations"], admissionExams: ["CUET", "State Aviation Entrance"], learningPlatforms: ["DGCA Resources", "Coursera", "ICAO Training"] },
  { id: "pilot", title: "Commercial Pilot Training (CPL)", category: "Aviation", interests: ["Aviation"], futureScope: "High", aiRisk: "Very Low", salary: "₹12L – ₹80L / year", startupPotential: "Low", globalDemand: "Very High", workLifeBalance: "Moderate", personalityMatch: ["discipline", "risk tolerance", "leadership"], streams: ["Science"], skills: ["Flight Operations", "Navigation", "Meteorology", "Aircraft Systems"], admissionExams: ["DGCA CPL Exam", "Class 1 Medical"], learningPlatforms: ["IGRUA", "CADET Programs", "DGCA"] },
  { id: "cabin-crew", title: "Diploma in Aviation Cabin Crew & Ground Operations", category: "Aviation", interests: ["Aviation", "Hospitality"], futureScope: "High", aiRisk: "Low", salary: "₹4.5L – ₹15L / year", startupPotential: "Low", globalDemand: "Very High", workLifeBalance: "Moderate", personalityMatch: ["communication", "discipline", "social confidence"], streams: ["Arts", "Humanities", "Commerce", "Science"], skills: ["Safety Procedures", "First Aid", "Customer Service", "In-flight Service"], admissionExams: ["Airline Selection Process", "Aptitude Test"], learningPlatforms: ["Frankfinn", "Airwing", "Coursera"] },
  { id: "aerospace-mgmt", title: "MBA Aviation & Aerospace Management", category: "Aviation", interests: ["Aviation", "Technology"], futureScope: "High", aiRisk: "Low", salary: "₹6L – ₹28L / year", startupPotential: "Good", globalDemand: "High", workLifeBalance: "Moderate", personalityMatch: ["leadership", "discipline", "analytical thinking"], streams: ["Science", "Commerce"], skills: ["Aerospace Economics", "Fleet Management", "Safety Management Systems", "MRO"], admissionExams: ["CAT", "GMAT", "RGNAU Entrance"], learningPlatforms: ["Coursera", "RGNAU", "LinkedIn Learning"] },
  { id: "atc", title: "Air Traffic Control (ATC) & Aviation Safety", category: "Aviation", interests: ["Aviation", "Technology"], futureScope: "High", aiRisk: "Very Low", salary: "₹8L – ₹25L / year", startupPotential: "Low", globalDemand: "High", workLifeBalance: "Moderate", personalityMatch: ["discipline", "analytical thinking", "risk tolerance"], streams: ["Science"], skills: ["Radar Operations", "Separation Standards", "Radio Communications", "Emergency Procedures"], admissionExams: ["AAI ATC Exam", "DGCA"], learningPlatforms: ["AAI Training", "ICAO", "Coursera"] },

  // ─── ADDITIONAL / CROSS-CATEGORY ─────────────────────────────────────────
  { id: "social-work", title: "Master of Social Work (MSW)", category: "Education", interests: ["Education", "Psychology", "Government Jobs"], futureScope: "Good", aiRisk: "Very Low", salary: "₹3L – ₹12L / year", startupPotential: "Moderate", globalDemand: "Moderate", workLifeBalance: "Good", personalityMatch: ["empathy", "communication", "emotional intelligence"], streams: ["Humanities"], skills: ["Community Development", "Case Management", "Advocacy", "Research"], admissionExams: ["TISS NET", "CUET", "State MSW Entrance"], learningPlatforms: ["IGNOU", "TISS", "Coursera"] },
  { id: "upsc-coaching", title: "UPSC / State PSC Coaching & Strategy", category: "Government Jobs", interests: ["Government Jobs", "Education"], futureScope: "Stable", aiRisk: "Very Low", salary: "₹6L – ₹24L / year", startupPotential: "Low", globalDemand: "High", workLifeBalance: "Moderate", personalityMatch: ["discipline", "leadership", "analytical thinking"], streams: ["Humanities", "Science", "Commerce"], skills: ["Polity", "History", "Geography", "Current Affairs"], admissionExams: ["UPSC CSE", "State PSC", "SSC CGL"], learningPlatforms: ["Unacademy", "BYJU's", "Khan Academy"] },
  { id: "banking-finance", title: "Banking & Financial Services (BFSI) Path", category: "Finance", interests: ["Finance", "Business", "Government Jobs"], futureScope: "High", aiRisk: "Moderate", salary: "₹4L – ₹22L / year", startupPotential: "Low", globalDemand: "High", workLifeBalance: "Good", personalityMatch: ["analytical thinking", "discipline", "communication"], streams: ["Commerce", "Science"], skills: ["Banking Operations", "Risk Assessment", "Loan Appraisal", "Regulatory Compliance"], admissionExams: ["IBPS PO", "SBI PO", "RBI Grade B"], learningPlatforms: ["Coursera", "JAIIB Study Material", "IBF"] },
  { id: "data-analyst", title: "BSc Data Analytics & Business Intelligence", category: "Technology", interests: ["Technology", "Finance", "Business"], futureScope: "Very High", aiRisk: "Low", salary: "₹5L – ₹22L / year", startupPotential: "Good", globalDemand: "Very High", workLifeBalance: "Good", personalityMatch: ["analytical thinking", "logical thinking", "discipline"], streams: ["Commerce", "Science", "Computer Science"], skills: ["Power BI", "Tableau", "SQL", "Excel Advanced"], admissionExams: ["JEE Main", "KEAM", "CUET"], learningPlatforms: ["DataCamp", "Google Analytics", "Coursera"] },
  { id: "cyber-forensics", title: "BSc Digital Forensics & Investigation", category: "Technology", interests: ["Technology", "Law"], futureScope: "Very High", aiRisk: "Very Low", salary: "₹6L – ₹28L / year", startupPotential: "Good", globalDemand: "High", workLifeBalance: "Good", personalityMatch: ["analytical thinking", "discipline", "logical thinking"], streams: ["Computer Science", "Science"], skills: ["Digital Evidence", "Malware Analysis", "Chain of Custody", "Computer Forensics"], admissionExams: ["JEE Main", "CLAT", "KEAM"], learningPlatforms: ["SANS Institute", "Cybrary", "Coursera"] },
  { id: "supply-chain-ops", title: "BSc Supply Chain & Logistics Operations", category: "Business", interests: ["Business", "Technology"], futureScope: "High", aiRisk: "Moderate", salary: "₹4L – ₹20L / year", startupPotential: "Good", globalDemand: "High", workLifeBalance: "Good", personalityMatch: ["analytical thinking", "teamwork", "discipline"], streams: ["Commerce", "Science"], skills: ["SCM Software", "Inventory Management", "Last Mile Delivery", "Analytics"], admissionExams: ["CUET", "MAT"], learningPlatforms: ["APICS", "Coursera", "Supply Chain Management edX"] },
];
